var Font_BingQiu="冰球";
var Font_QingDengLu="請你登錄後再進入本站！";
var Font_XiTongMaLu3="報表系統維護中，造成不便，敬請見諒！！！";
var Font_XiTongMaLu2="系統忙碌中...請 稍 候...";
var Font_XiTongMaLu1="系統忙碌中 , 造成不便 , 敬請見諒 !!!";
var Font_XiTongMoRen="系統默認";
var Font_ShuRuBuNengWeiKong="輸入不能為空！";
var Font_QingXuanZeGuoGuanShu="請選擇2-10個過關";
var Font_XinYongEDu="信用額度";
var Font_QiTaBangQiu="其他棒球";
var Font_XiTongWeiHu="手機版頁面維護中";
var Font_WeiDaManJiuJu="局數不正規";
var Font_TeDing15="特定15分";
var Font_SuoYouDuiZhan="九卅對戰(細項)";
var Font_RangFenTeam="讓分隊伍";
var Font_FenLeiXiangMu="分類項目";
var Font_Chatroom="聊天室";
var Font_SaiMaFenXi="賽馬分析";
var Title_ZhuBoSontLi="主播送禮";
var Font_BingQiu2="冰&nbsp;球";
var Font_BingQiu1="冰球";
var Font_BenGongSiWangZhi="本公司已更改網址.\n新網址為";
var Font_TaiWanSanXingCai="台灣三星彩";
var Font_GuanKanYingPMobile="觀看影片";
var Font_WuXuanBuZhong="五選不中";
var Font_JumpPage="搜尋頁簽";
var Font_ShangBanChang="上半場";
var Font_KeYongEDuMobile="可用額度";
var Font_TouZhuEDuWK="投注額度不可以爲空！";
var Font_QDJSFPDXZLTS="請點擊上方頻道選擇聊天室";
var Font_ChaZhao1="查&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;找";
var Font_TouZhuJuJue="投注拒絕";
var Font_YiBeiJuJue="";
var Font_OZB2016="歐洲杯";
var Font_JiNuoCai="基諾彩";
var Font_GunQiuDanShuang="滾球單雙";
var Font_TeBieHao="特別號";
var Font_ShiWeiShu="十位數";
var Font_TouZhuXinXi="投注信息";
var Font_PanKouDZB="盤口對照表";
var Font_CreditBetIsSuccess="下注成功！\n請至[即時注單]查詢！";
var Font_WoDeZuiAi="我的最愛";
var Font_ZhongGuoMeiRen2="中&nbsp;國&nbsp;美&nbsp;人";
var Font_ZhiShuGongGao1="";
var Font_ZhangHuYuE="帳戶餘額";
var Font_SaiShiDaiDing="賽事待定";
var Font_CMDJKDS="亞投體育加扣點";
var Font_ZhuDanZhuangKuang="注單狀況";
var Font_BeiJingSaiChe="北京賽車";
var Font_YiShang="以上";
var Font_BenZhouHeJi="本週合計";
var Font_HuiYuanZhangHaog2="會員帳號";
var Font_PhoneAD="廣告剩餘時間";
var Font_ZhuDanShengHeZhong="正在審核您的注單，請注意您的注單狀態";
var Font_MeiYouQuanXian="您沒有進入權限，請洽詢客服人員！";
var Font_RangQiu2="讓球";
var Font_SunbetPointsChanged="申博加扣點";
var Font_RangFen2="讓分";
var Font_RangFen1="讓分";
var Title_SongLiContent="內容";
var Font_PanKouGuanBiZ="盤口關閉中......";
var Title_GameBill_GetSmallMoney="獲得小彩金：";
var Font_PingDao="頻道";
var Font_YouXiXML2="遊戲洗碼量";
var Font_ErXingZuXuan="二星組選";
var Font_YouXiJinE="遊戲金額";
var Font_LiShiTouZhuMX="歷史投注明細";
var Font_XiaBanChangGQDS="下半場<br />滾球單雙";
var Font_XiaBanChangGQDX="下半場<br />滾球大小";
var Font_XiaBanChangGQRF="下半場<br />滾球讓分";
var Font_XiaBanChangGunQ="下半場滾球";
var Font_ZhongDong="註：中洞需自行輸入球頭";
var Font_TianDiPeng="天地碰";
var Font_MeiShiPeiLv2="美式賠率";
var Font_MeiShiPeiLv3="美式賠率";
var Font_CheMaPao="車馬炮";
var Font_CD658658="大傳奇科技王---會員介面";
var Font_NinXiaZhuDePLBH="您下注的賠率發生變化！";
var Font_TiYuYouXiaoTouZhu="體育<br/>有效投注";
var Font_Tiger777="TIGER 運動網---會員介面";
var Font_Tiger888="TIGER 運動網---會員介面";
var Font_YuSheDanShiTouZhuJE="預設單式投注金額";
var Font_SiNuoFaKe="斯诺伐克";
var Font_DiBaMing="第八名";
var Font_BeiJingShiJian="北京時間";
var Font_XiuGaiShiBai2="賬號密碼規格不符合，請重新輸入6-10位英文和數字，前2位必須是英文！";
var Font_XiuGaiShiBai1="修改失敗，您輸入的密碼與舊密碼相同！";
var Font_KaiFangGuoGuan="對不起，您沒有開放過關！";
var Font_ZhiShuGongGao="指數公告";
var Font_CQ_Hundreds="百位";
var Font_ErZhongE="二中二";
var Font_ErZhongT="二中特";
var Font_TiYuXinYongEDu="體育信用額度";
var Font_AoMenSaiGou="澳門賽狗";
var Font_XHYLJDFS="新會員禮金";
var Font_ErZhongEr="2星(二中二)";
var Font_BaiJinMember="白金會員";
var Font_MingCheng="名稱";
var Font_BangQiu="棒球";
var Font_JiangXingJiSuan="降星計算";
var Font_PiaoHaoYSDSTZJE1="選擇啟用,將以設定後的金額投注單式及滾球賽事(數值不能低於3位,高於6位).";
var Font_PiaoHaoYSDSKYJE1="選擇啟用,將以設定後的可贏金額投注單式及滾球賽事(數值不能低於3位,高於6位);";
var Font_21Dian2="21&nbsp;點";
var Font_JiShiZhuDan="即時注單";
var Font_SaiGuChuiNiu6="骰盅吹牛6";
var Font_SaiGuChuiNiu3="骰盅吹牛3";
var Font_SaiGuChuiNiu2="骰&nbsp;盅&nbsp;吹&nbsp;牛";
var Font_GengHuanYanZhengMa="看不清楚請按這裡更換驗證碼";
var Font_GuoJiPeiLv="國際賠率";
var Font_BanChangRangQiu1="";
var Font_BanChangRangFen1="";
var Font_Confirming="確認中";
var Font_JinRuLiaoTianShi="進入聊天室";
var Font_DiErJieMobile="第二節";
var Font_SanQuanZhong="3星(三全中)";
var Font_ZuiXinWuBiZhuDan="最新五筆注單";
var Font_QiangWeiFen4="搶尾分";
var Font_QiangWeiFen3="搶尾分";
var Font_QiangWeiFen2="搶尾分";
var Font_QiangWeiFen1="搶尾分";
var Font_ShuaXin="刷新";
var Font_Shuang1="雙";
var Font_ShuYing="輸贏";
var Font_QiMaWeiShu="七碼位數";
var Font_JiangHaoFangWei="獎號方位";
var Font_ShangYe="上頁";
var Font_ShanChu="刪除";
var Font_JiaKouDianShu="加扣點數";
var Font_MoRenTouZhuKeYingJE="默認投注可贏金額";
var Font_ShouQiu="手球";
var Font_ShiXun2="視&nbsp;訊";
var Font_ShiJian="時間";
var Font_WXXiaBanSX="下半";
var Font_BaiJiaLe2="百&nbsp;家&nbsp;樂";
var Font_MinBetMoneyElement="元";
var Font_GuoGuanJSQ="過關計算器";
var Font_SaiShiZhiBo="賽事直播";
var Font_YuLeChang="娛樂場";
var Font_CaiQiuZhuDan="彩球注單";
var Font_XiaZhuFangShi="下注方式";
var Font_SiZhiDao="四支刀";
var Font_ZhiBoLTSYJDK="直播聊天室已經打開！";
var Font_JiaZaiBoFangQZ="加載播放器中";
var Font_BaoCunXiuGai="保存修改";
var Font_GunQiuDaXiao2="滾球大小";
var Font_XuanZeXSLM="選擇聯賽";
var Titile_ZhuBoJiShi="主播即時注單";
var Tilte_NewVersion="切換新版";
var Font_DiYiJuWinner="第一局獲勝者";
var Titile_ZhuBoLiShi="主播歷史帳務";
var Font_XinTuiTongZi="新推筒子";
var Font_ShiYongZHWCGN="試用帳號無此功能！";
var Font_KeYingJinE="可贏金額";
var Font_ZuiJiaPeiLv="最佳賠率";
var Font_LanQiu2="籃&nbsp;球";
var Font_LanQiu1="籃球";
var Font_ZuQiuGongGao="足球公告";
var Title_Bill_XiaZhu="下注";
var Font_DanJieZuiGaoDF="單節最高得分";
var Font_BeiJing="北京";
var Font_ShuangXingLZP="雙星連柱碰";
var Font_ShouCangJiaXianZhi="尊敬的會員您好，收藏夾目前已達最高限制！";
var Font_TianJing="田徑";
var Font_JiJiangKaiSai="即將開賽";
var Font_TaiWanJNC="台灣基諾彩";
var Font_TaiWan539="台灣539";
var Font_NinDeJinYanRenShuYiDaShangXian="您的禁言人數已達上限！";
var Font_YiChangDengRu="您的賬號異常登入";
var Font_BetOver="下注大分";
var Font_PeiLvJiShiGengXin="賠率即時更新";
var Font_PanShu1="盤數";
var Font_QingZhiShaoXZLG="請至少選擇兩關";
var Font_WeiXiaZhuSM="您于48小時內未下注，將以訪客身份進入聊天室，造成不便，敬請見諒!!!";
var Font_WeiKaiJiang="未開獎";
var Font_ZuiShaoXZYiZhangBiSai="最少選擇一種比賽類型!";
var Font_1151="1/1.5";
var Font_1152="一球/一球半";
var Font_1153="1-50";
var Font_10c1="10串1";
var Font_1501="1.5/2";
var Font_1503="2+50";
var Font_1502="一球半/二球";
var Font_3_51="3.5";
var Font_3_52="三球半";
var Font_3_53="3輸";
var Font_1XBZ="一肖不中";
var Font_1Shu="1.5";
var Font_0051="0/0.5";
var Font_0052="平手/半球";
var Font_0053="0-50";
var Font_0501="0.5/1";
var Font_0502="半球/一球";
var Font_0503="1+50";
var Font_2251="2/2.5";
var Font_2252="二球/二球半";
var Font_2253="2-50";
var Font_7PK2="7&nbsp;P&nbsp;K";
var Font_4c11="4串11";
var Font_2_51="2.5";
var Font_2_53="2輸";
var Font_2_52="二球半";
var Font_5c26="5串26";
var Font_5PK2="5&nbsp;P&nbsp;K";
var Font_HeHe="和/和";
var Font_HeKe="和/客";
var Font_HeJi="合計";
var Font_HeJu="和局";
var Font_Hong="紅";
var Font_Hou2="猴";
var Font_HP66="快樂運動網---會員介面";
var Font_6c57="6串57";
var Font_Long="龍";
var Font_Lose="全輸";
var Font_Line="分盤";
var Font_MiMa="密碼";
var Font_Miao="秒";
var Font_LSZW="歷史帳務";
var Font_KeHe="客/和";
var Font_KeKe="客/客";
var Font_AnQi="暗棋";
var Font_DiVI="第";
var Font_Dian="點";
var Font_Dan1="單";
var Font_DanT="单T";
var Font_DaiD="待定";
var Font_Chat="客";
var Font_Xing="星";
var Font_Xia1="下";
var Font_Xiao="小";
var Font_Xian="線";
var Font_Yuan="(元)";
var Font_Yang="羊";
var Font_YeVI="页";
var Font_GQQR="確&nbsp;&nbsp;&nbsp;認";
var Font_Gong="共";
var Font_FSZu="組";
var Font_Guan="關";
var Font_FSBi="筆";
var Font_FSCG="複式串關";
var Font_Ping="平";
var Font_Peng="碰";
var Font_Quan="全";
var Font_QiTa="其他";
var Font_Qian="千";
var Font_TiYu="體育";
var Font_TeMa="特碼";
var Font_SSSJ="賽事數據";
var Font_Rang="讓";
var Font_Shu2="鼠";
var Font_Shui="水";
var Font_Shou="首";
var Font_Wei2="尾";
var Font_Wei1="尾";
var Font_Wan1="萬";
var Font_Wan3="萬";
var Font_Wan2="萬";
var Font_XinMiMaBuNWK="新密碼不能為空！";
var Title_Bill_Result="結果";
var Font_OddsCannotBeEmpty="賠率不能為空";
var Font_GuanYaHeZhi="冠亞軍和值";
var Font_LiuXuanZhongYi="六選中一";
var Font_BanChangDuYingHGQ1="";
var Font_BanChangDuYingHGQ2="半場獨贏<br />（含滾球）";
var Font_ShiJieBei="世界杯";
var Font_DiYiJieMobile="第一節";
var Title_Bill_Content="投注";
var Font_JiaNaDaXB="加拿大西部";
var Font_SongChu="送出";
var Font_JiYiCiZhangHao="記憶此帳號";
var Font_BetAmountCanbeBlank="投注金額不能為空！";
var Font_GunQiuBoDan2="全場/半場<br/>波膽<br/>（含滾球）";
var Font_ZhiXianShiYXZD="只顯示遊戲注單";
var Font_ZhiXianShiTYZD="只顯示體育注單";
var Font_XiaZhuChengGong1="下注成功";
var Font_ZhenRenLongHu="真人龍虎";
var Font_FSCGMQMYCXD="目前沒有查詢到相應的子單";
var Font_GengDuoWanFa="更多玩法";
var Font_WeiXianDengJi6="危六";
var Font_WeiXianDengJi5="危五";
var Font_WeiXianDengJi4="危四";
var Font_WeiXianDengJi3="危三";
var Font_WeiXianDengJi2="危二";
var Font_WeiXianDengJi1="危一";
var Font_QianWeiShu="千位數";
var Font_FastBetOpen="您已開啟<span class='Info_Note02'>快速下注</span>模式</span><br /><span class='Info_Note03'>設置投注金額後<br />點擊賠率即刻進行投注";
var Font_SuoYouYunDong="九卅體育(細項)";
var Font_InputMin2="請輸入最少2位小數";
var Title_Bill_TouZhu="投注";
var Font_YiZhongYiPeiLv="一中一賠率";
var Font_GunQiuGXMS="滾球更新秒數";
var Font_GunQiu1Shu="滾球1輸";
var Font_QingXuanZeZDZK="請選擇注單狀況";
var Font_QingXuanZeZDLX="請選擇注單類型";
var Font_QingXuanZeZwrq="請選擇帳務日期";
var Font_SanXiaoLianZhong="三肖連[中]";
var Font_BanChangDuYing1="";
var Font_XiaZhuShiJian="下注時間";
var Font_TaiBangMobile="台棒";
var Font_TurnOff="關";
var Font_LianMaKuaiSu="連碼快速";
var Font_XiaZhuMiaoShuSD="下注秒數鎖定...請重新下注...";
var Font_YiShanChu="已刪除";
var Font_YiBanHuiYuan="一般會員";
var Font_DuoXuanZhongYi="多選中一";
var Font_DuoZhongWanFa="多種玩法";
var Font_XiuGaiChengGong="修改成功！請牢記您的密碼！";
var Font_SaiBao2="骰&nbsp;寶";
var Font_SiZhiDao2="四&nbsp;支&nbsp;刀";
var Font_SanXing="三星";
var Font_SanGong="三公";
var Font_DiQiMing="第七名";
var Font_ZuoRiNinMeiYQLZD="昨日您沒有球類注單.";
var Font_ZuoRiNinMeiYYXZD="昨日您沒有遊戲注單.";
var Font_MuQianWuZhuDan="目前無注單.";
var Font_WXShangGun="上滾";
var Font_WXShangBan="上半";
var Font_ClickSelection="點擊投注項目";
var Font_PengShu="碰數";
var Font_LiuMaWeiShu="六碼位數";
var Font_YiQueRen="已確認";
var Font_ZiDongJieShouPL="自動接受賠率";
var Font_DiWuMing="第五名";
var Font_YongHuJinDeng="該用戶已被禁止登陸！";
var Font_JinPingMei2="金&nbsp;瓶&nbsp;梅";
var Font_DianJiZhanKai="點擊展開";
var Font_TeBieTouZhu="特別投注";
var Font_WuZhiQi="五子棋";
var Font_ChaoChuFanWei="超出範圍，請重新輸入搜尋條件！";
var Font_JiXuXiaZhu="繼續添加";
var Font_LiuXuanBuZhong="六選不中";
var Font_GunQiuRuQiuShu="滾球入球數";
var Font_MiaoHouZiDongGX="秒後自動更新";
var Font_QiuleiZhuDan="球類注單";
var Font_MiMaQueRen="密碼確認";
var Font_QianSanQBS="前三[千百十]";
var Font_QianSanWQB="前三[萬千百]";
var Font_10Xing="十星";
var Font_BenChangZongZhuE="本場總注額";
var Title_Bill_PaiCai="派彩";
var Font_BangQiuGongGao1="";
var Font_BanQuanChang="半全場";
var Font_TodayNoContest="今日無賽事";
var Font_YiTuiChu="已退出";
var Font_SystemMessage="系統信息";
var Font_MiMaChangDuXY="密碼長度小於4位！";
var Font_PiaoHaoYSGGTZJE="選擇啟用,將以設定後的金額投注過關及綜合過關賽事(數值不能高於6位).";
var Font_PiaoHaoYSGGKYJE="選擇啟用,將以設定後的可贏金額投注過關及綜合過關賽事(數值不能高於6位).";
var Font_ABPointsChanged="歐博加扣點";
var Font_GunQiuDuYing="滾球獨贏";
var Font_XiTongZiTi="系統字體";
var Font_XinJiangShiShiCai="新疆時時彩";
var Font_PiaoHaoYSDSTZJE="選擇啟用,將以設定後的金額投注單式及滾球賽事(數值不能低於2位高於6位).";
var Font_PiaoHaoYSDSKYJE="選擇啟用,將以設定後的可贏金額投注單式及滾球賽事(數值不能低於2位高於6位);";
var Font_QiangWeiFen="搶尾分";
var Font_ZuiZhongJieGuo="最終結果";
var Font_KaiXiFenQuanKou="開洗分全扣";
var Font_GunQiuDaXiao="滾球大小";
var Font_ZheShiGunQiu="這是滾球投注";
var Font_XiuGaiMiMa="修改密碼";
var Font_TouZhu2="投注";
var Font_TouZhu3="投注";
var Title_XianChangZhaunBo="九卅體育--現場轉播";
var Font_RiBangMobile="日棒";
var Font_YongHuSuoDing="該帳戶已被鎖定!";
var Font_YouXiGongGao="遊戲公告";
var Font_JuShangBan="局&nbsp;上半";
var Font_SuoYouZhuDan="所有注單";
var Font_DiSanZhu="第三柱:";
var Font_DiSanPan="第三盤獲勝者";
var Font_DiSanJie="第三節";
var Font_DiSiJie2="第四節";
var Font_DiSiMing="第四名";
var Font_YuSheDanShiKeYingJE="預設單式可贏金額";
var Font_Mei60MiaoGX="每60秒更新";
var Font_FSCGTZZHLB="投注組合列表";
var Font_MeiDianJinE="每點金額";
var Font_MeiZuGongGao="美足公告";
var Font_ZhiBoSaiShiJieShuHDT="該賽事已結束,自動跳轉回大廳！";
var Font_Rejected="投注拒絕";
var Font_QiangShouFen4="搶首分";
var Font_QiangShouFen1="搶首分";
var Font_QiangShouFen3="搶首分";
var Font_QiangShouFen2="搶首分";
var Font_FSCGMYXSYBZ="每頁顯示100組";
var Font_WXQuanChang="全場";
var Font_BetAccepted="投注完成";
var Font_AGJiaKouDian="";
var Font_ZiDongJieShouZJPL="自動接收最佳賠率";
var Font_ZiDongJieShouRHPL="自動接收任何賠率";
var Font_BaiWeiShu="佰位數";
var Font_JiuXuanBuZhong="九選不中";
var Font_CQ_Unit="个位";
var Font_ErBaGang2="二&nbsp;八&nbsp;槓";
var Font_ZunLongMember="尊龍會員";
var Font_LiZhuKuaiSu="立柱快速";
var Font_PiaoHaoZDJSPL="選擇任何賠率,若投注過程中若賠率有變好或變差,則直接投注成功;<br />選擇最佳賠率,若投注過程中若賠率有變好,則以最佳賠率投注,若賠率有變差,則跳提示框告知.";
var Font_PiaoHaoZDSXPL="選擇啟用,投注視窗每10秒更新賠率;選擇不啟用將不自動更新.";
var Font_SanZhongEr="三中二";
var Font_21Dian="21點";
var Font_DiYiMing="第一名";
var Font_DiYiJie2="第1節";
var Font_DiYiJie3="第一節";
var Font_PHMeiShiPL="美式赔率";
var Font_LunPan2="輪&nbsp;盤";
var Font_QuanBuXianShi="全部顯示";
var Font_20Bets="20筆";
var Font_SaiGouSaiQiBiao="賽狗賽期表";
var Font_TouZhuNeiRong="投注內容";
var Font_ZhuiZongJieGuo="最終結果";
var Font_ZhuDanBianHao="注單編號";
var Font_YinCangYuE="隱藏餘額";
var Font_YinCangLTS="隱藏聊天室";
var Font_CKGNZBKF="很抱歉 目前存款功能暫不開放 謝謝!";
var Title_ShiShiZhuDan="即時注單";
var Font_NotNewNoteSingle="沒有最新注單";
var Font_SanZhongErPeiLv="三中二賠率";
var Font_TouZhuJuJueVI="";
var Font_SanXingZuXuanLiu="三星組選六";
var Font_SanXingZuXuanSan="三星組選三";
var Font_SaiGuChuiNiu3Ren="骰盅吹牛3人";
var Font_BuGengXin="不更新";
var Font_WordDescriptions="文字說明";
var Font_DanZhuShangXian="單注上限";
var Font_QueRenTouZhuNR="確認投注";
var Font_ShangZhongXia="上中下";
var Font_ZanShiMeiYouSPLSJL="暫時還沒有收盤價歷史記錄";
var Font_MiPaiBaiJiaLe="竞眯";
var Font_ShangZhouHeJi="上週合計";
var Font_TouZhuHouTYSSMS="投注後體育賽事模式";
var Font_ZuGaoTouZhuEr="最高投注額";
var Font_ZhaoYunJiuZhu="趙雲救主";
var Font_MeiYeXianShi100B="每頁顯示100筆";
var Font_TongZuHeZGKYJE="同組合最高可贏金額";
var Font_YuLeChangWeiHu="目前娛樂場維護中,請稍後再進入,謝謝!";
var Font_TiYuEDu="體育額度";
var Font_XiTongGongGao1="";
var Font_MeiBangGongGao="美棒公告";
var Font_MingCheng2="名  稱";
var Font_40Bets="40筆";
var Font_MiMaXiuGai="密碼修改";
var Font_PiaoHaoSSMS="選擇最新注單,每次投注成功後,左側賽事欄位顯示為最新注單介面;<br />選擇展開體育,每次投注成功後,左側賽事欄位顯示為體育賽事介面.";
var Font_PiaoHaoPLLX="選擇賠率類型, 賠率加總為1.90國際賠率則為0.95/0.95顯示,美式賠率則為-105/-105顯示.";
var Font_PiaoHaoPXMS="選擇模式聯盟排序,各球類賽事頁面依照同聯盟賽事排列在一起.";
var Font_PiaoHaoGQGX="選擇10秒,各球類滾球(包括滾球中心)賽事頁面自動刷新秒數為10秒.";
var Font_PiaoHaoDRSY="選擇首頁球類,進入體育博彩頁面預設顯示為首頁球類的賽事.";
var Font_PiaoHaoXSQRXX="選擇啟用,每次投注時,系統跳出下注確認資訊提示框,點擊確認後才能正常投注.";
var Font_PiaoHaoXSCGXX="選擇啟用,每次投注成功後,系統跳出投注成功提示框.";
var Font_DiSanJuWinner="第三局獲勝者";
var Font_XiaBanChang2="下半場";
var Font_TiCaiP3="體彩P3";
var Font_DangQianYanSe="當前顏色";
var Font_HanLan="韓籃";
var Font_DanShuang="單雙";
var Font_HeXiao="合肖";
var Font_JiuXuanZhongYi="九選中一";
var Font_ShouMobile="首";
var Font_ChuanGuan="串關";
var Font_TianSan="天三";
var Font_TiaoZhi="跳至";
var Font_QingNinShuRuZQDSZ="請您輸入正確的數值！";
var Font_DuiWuSuoDingZhong="隊伍鎖定中......";
var Font_TaiWanCaiQuanJG="台灣彩券結果";
var Font_60Bets="60筆";
var Font_CQ_Extra2="2區特別號";
var Font_SiNuoFaKeJNC="斯諾伐克基諾彩";
var Font_CaiQiuGongGao="彩球公告";
var Font_GunQiuBanQuanChang="滾球半全場";
var Font_XuanZeXSLM2="選擇聯賽";
var Font_XuanZeDuiWu="選擇隊伍";
var Font_TuanTiXiaZhuTLQX="團體下注取消";
var Font_YiMobile="一";
var Font_ZuiGaoTouZhuEMobile="最高投注額";
var Font_YiShiJianPX="時間排序";
var Font_ChongXinXiaZhu="請重新下注";
var Font_RenHePeiLv="任何賠率";
var Font_ShengXiaoLian="生肖連";
var Font_Mei30MiaoGX="每30秒更新";
var Font_QuXiao2="取消";
var Font_SuoYouCaiQiu1="所有彩球";
var Font_ZhenRenPaiJiu2="真&nbsp;人&nbsp;牌&nbsp;九";
var Font_HideTiYuSaiShi="隱藏體育賽事";
var Font_DianZiYouXi="電子遊戲";
var Font_ShouBiBaiJiaL="手臂百家樂";
var Font_PHShiJianPX="時間排序";
var Font_FangWei="方位";
var Font_FanTan2="番&nbsp;攤";
var Font_QueDing="確定";
var Font_FanShui="返水";
var Font_QuanChe="全車";
var Font_QuanBu1="全&nbsp;&nbsp;&nbsp;部";
var Font_ExampleWords="例：洋基1+80 紅襪，比賽結束 2:1，下注洋基：選擇 ( + )填入80，下注紅襪：選擇 ( - )，填入80";
var Font_GeRenXunXi="個人訊息";
var Font_ChangCi="場次";
var Font_BangQiu1="棒球";
var Font_ChaKan2="查看";
var Font_ChaZhao="查找";
var Font_BaiJiaLe="百家樂";
var Font_BaiJinJi="白金級";
var Font_QinWuShuRuFeiFaZiFu="請勿輸入非法字符";
var Font_LanQiu="籃球";
var Font_WeiKaiFang="(未開放)";
var Font_LongHu="龍虎";
var Font_Winning="可贏金額";
var Font_BaiShiGe="百十個";
var Font_LiuYan="留言";
var Font_YingXiong2="英&nbsp;雄";
var Font_FSCGTZEWN="投注額度為0，請重新下注！";
var Font_FSCGTZEGD="投注額過低，點擊“確定” \n\n紅框將會更改最低金額！";
var Font_ErBaGang="二八槓";
var Font_LunPan="輪盤";
var Font_GqBetInfo="滾球投注訊息";
var Font_AlertSwitchLine2="線路已重新調配，系統將為您切換至最佳線路";
var Font_QuanChang2="全場";
var Font_NinZanShiWuFXZ="您暫時無法下注！";
var Font_YuSheTouZhuJinE="預設投注金額";
var Font_BanDiQiu="班迪球";
var Font_MeiLan="美籃";
var Font_MeiZu2="美&nbsp;足";
var Font_MeiZu1="美足";
var Font_JiaNaDaXBJNC="加拿大西部基諾彩";
var Font_AoMenSaiQiBiao="澳門賽期表";
var Font_MaMing="馬名";
var Font_WXQuanGun="全滾";
var Font_BetValueCanTbeGreaterThanremainingAmount="投注額度不可以大於剩餘額度";
var Font_FSCGTZEDBKDY="投注額度不可大於";
var Font_XiYouJi2="西&nbsp;遊&nbsp;記";
var Font_JiaNaDaJNC="加拿大基諾彩";
var Font_MinBet="最低押注";
var Font_MingCi="名次";
var Font_TSYunDongWang="TS運動網---會員介面";
var Font_InPlayBettingReminder="滾球投注資訊";
var Font_KaiFenZengSong="开分赠送";
var Font_NoteWord="注意事項";
var Font_BiSaiShiJian="比賽時間";
var Font_DianCiJinRuTLQ="點此進入討論區";
var Font_PHSaiMa="賽馬/賽狗";
var Font_YiShuErYing1="一輸二贏";
var Font_YiShuErYing2="一輸二贏";
var Font_WithdrawalTitle="提款";
var Font_BiShaiJieGuo="比賽結果";
var Font_WXDanGao="單高";
var Font_JiHeOu="奇和偶";
var Font_JiaJie="加時";
var Font_JieGuo="結果";
var Font_ZuanShiJi="鑽石級";
var Font_XiangGangSaiMa="香港賽馬";
var Font_GunQiuZhongXin="滾球中心";
var Font_JuShu1="局數";
var Font_JuShu2="局數";
var Font_GuangChang="廣場";
var Font_NinFaSongPLGK="您發送頻率過快，請3秒后重新發送";
var Font_SaiMaResult="賽馬/賽狗";
var Font_DuChengDaHeng="賭城大亨";
var Font_KeYing="可贏";
var Font_PaiXuMoShi="排序模式";
var Font_PHMeiZu="美足";
var Title_Bill_BiSai="比賽";
var Font_ZhenRenShouBi="(真人+手臂)";
var Title_Results="比賽結果";
var Font_ZongFenWinner="總分獲勝者";
var Font_GuanFangWangZhanYP="官方網站影片";
var Font_DiJiuMing="第九名";
var Font_QiuLei2="球   類";
var Font_Calculate="計算";
var Font_QianBai="千百";
var Font_SuoYouDuiZhan1="所有對戰";
var Font_ZiTiXZGJL="字體選擇工具欄";
var Font_ZiTiYanSe="顏色";
var Font_TaiWanErBaGang="台灣二八杠";
var Font_WeiZhiQ="位置Q";
var Font_ZhenRenPaiJiu="真人牌九";
var Font_QingZhi="請至";
var Font_QingXie="傾斜";
var Font_XizZhuSibaiQCXXZ="下注失敗請重新下注！";
var Font_DiYiJieRangFen1="";
var Font_ZhenRenBaiJiaLe="真人百家樂";
var Font_Week_Er="二";
var Font_Week_Yi="一";
var Font_Week_Ri="日";
var Font_Week_Si="四";
var Font_Week_Wu="五";
var Font_QuanBuGongGao="全部公告";
var Font_YuMaoQiu="羽毛球";
var Font_YaFenShangXiaXian="押分上下限";
var Font_XinJiaPoSaiQiBiao="新加坡賽期表";
var Font_TaiBang="台棒";
var Font_WuYuanSu="五元素";
var Font_QiXuanBuZhong="七選不中";
var Font_Confirm="確認";
var Font_WuXuanZhongYi="五選中一";
var Font_Amount="下注金額";
var Font_Accept="接受";
var Font_48XiaoShiWeiXiaZhu="您如果於48小時內未下注 ,將無法進入觀看各類精彩影片 , 造成不便 , 敬請見諒 !!!";
var Font_QianBaiShi="千百十";
var Font_XingQiLiu="星期六";
var Font_XingQiSan="星期三";
var Font_ZhenRenBaiJiaLe2="真&nbsp;人&nbsp;百&nbsp;家&nbsp;樂";
var Font_60Srefresh="60秒更新";
var Font_FuWuGuiZe="服務規則";
var Font_DanShuangHGQ1="";
var Font_LanQiuGongGao="籃球公告";
var Font_XuanzeWanfa="選擇玩法";
var Font_SaiMaWeiZhi="賽馬位置";
var Font_DianJiXiaZhu="點擊下注";
var Font_GuangDongKaiXinCai="廣東開心彩";
var Title_XianGuanWangZhan="九卅體育--相關網站";
var Font_JinYanChengGong="禁言成功！";
var Font_WuZhiQi2="五&nbsp;子&nbsp;棋";
var Font_QingZhuCeHuiYuan="請註冊會員後方能觀看免費影片";
var Font_RiBangGongGao="日棒公告";
var Font_SanXiaoLianBuZhong="三肖連[不中]";
var Font_NiuNiu="牛牛";
var Font_MeiBang="美棒";
var Font_FSCGGTZ_EN="個投注";
var Font_CaiQiu2="彩&nbsp;球";
var Font_CaiQiu1="彩球";
var Font_DiLiuMing="第六名";
var Font_WeiXianDengJi="危險等級";
var Font_BaiJiaLeJackpotS2="手&nbsp;臂&nbsp;百&nbsp;家&nbsp;Jackpot";
var Font_ExceededTheGameMax="已超過本場總注額";
var Font_TaiWanSiXingCai="台灣四星彩";
var Font_ZhenRenLongHu2="真&nbsp;人&nbsp;龍&nbsp;虎";
var Font_QueRenXiaZhuMobile="確認投注";
var Font_PayableAmount="輸付金額";
var Title_Bill_Info="帳務日期";
var Title_Bill_YuEr="餘額";
var Title_Bill_Type="類型";
var Font_PleaseEnterTheAmount="請輸入本金！";
var Font_GuoGuanShu_Guan="關";
var Font_GuoGuanShu_Gong="共";
var Font_JieChuJinYanChengGong="解除禁言成功！";
var Font_WanQian="萬千";
var Title_GongGaoXunXi="九卅體育--公告訊息";
var Font_7HuoYiShang="7或以上";
var Font_DiXQiu="第几球";
var Font_DiYiYe="第一頁";
var Font_WangQiu="網球";
var Font_DianZi="電子";
var Font_ShuaXinYiQueRen="請重複按<span class='color_red'>刷新</span>已確認您的投注";
var Font_DengDaiZhong="等待中";
var Font_DengRu="登  入";
var Font_ZhengFuJiXian="正負極限";
var Font_SaiShiYiJieShu="賽事已結束";
var Font_DaXiao="大小";
var Font_DaTing="大廳";
var Font_DanJie="單節";
var Font_DanHao="單　　號:";
var Font_DanShu="單數";
var Font_DanShi="單式";
var Font_DuYing="獨贏";
var Font_TongZuHeZGPC="最高可贏金額";
var Font_BaiJiaLeJackpot="百家jackpot";
var Font_XianShangKeFu="線上客服";
var Font_WenZiMiaoShu2="表示<span class='MFS_colorB'>讓分隊伍</span>贏<span class='MFS_colorG'>受讓隊伍</span>3分時，兩隊平手，4分全贏。";
var Font_WenZiMiaoShu3="表示<span class='MFS_colorB'>讓分隊伍</span>贏<span class='MFS_colorG'>受讓隊伍</span>3分時，押<span class='MFS_colorB'>讓分隊伍</span>贏50%，4分全贏。";
var Font_WenZiMiaoShu1="表示<span class='MFS_colorB'>讓分隊伍</span>贏<span class='MFS_colorG'>受讓隊伍</span>3分時，押<span class='MFS_colorB'>讓分隊伍</span>輸50%，4分全贏。";
var Font_WenZiMiaoShu6="表示<span class='MFS_colorB'>讓分隊伍</span>贏<span class='MFS_colorG'>受讓隊伍</span>2分時，兩隊平手，3分全贏。";
var Font_WenZiMiaoShu7="表示<span class='MFS_colorB'>讓分隊伍</span>贏<span class='MFS_colorG'>受讓隊伍</span>2分時，押<span class='MFS_colorB'>讓分隊伍</span>贏50%，3分全贏。";
var Font_WenZiMiaoShu4="表示<span class='MFS_colorB'>讓分隊伍</span>贏<span class='MFS_colorG'>受讓隊伍</span>2分時，押<span class='MFS_colorB'>讓分隊伍</span>全輸，3分全贏。";
var Font_WenZiMiaoShu5="表示<span class='MFS_colorB'>讓分隊伍</span>贏<span class='MFS_colorG'>受讓隊伍</span>2分時，押<span class='MFS_colorB'>讓分隊伍</span>輸50%，3分全贏。";
var Font_WenZiMiaoShu8="表示<span class='MFS_colorB'>讓分隊伍</span>贏<span class='MFS_colorG'>受讓隊伍</span>1分時，押<span class='MFS_colorB'>讓分隊伍</span>全輸，2分全贏。";
var Font_WenZiMiaoShu9="表示<span class='MFS_colorB'>讓分隊伍</span>贏<span class='MFS_colorG'>受讓隊伍</span>1分時，押<span class='MFS_colorB'>讓分隊伍</span>輸50%，2分全贏。";
var Font_CaiQiuXiMaLiang="彩球<br/>洗碼量";
var Font_MaJiang="麻將";
var Font_ErXing="二星";
var Font_QuanChangBiShu="全場比數";
var Font_SaiMaSaiGuo="賽馬賽果";
var Font_ErXiaoLianBuZhong="二肖連[不中]";
var Font_NiQueDingYaoXZM="您確定要下注嗎?";
var Font_BiaoTi="標題";
var Font_PaiChaiShiJian="派彩時間";
var Font_YouXiXML="遊戲<br/>洗碼量";
var Font_Week_Liu="六";
var Font_Week_San="三";
var Font_BaiJia="百家";
var Font_BaiShi="百十";
var Font_BeiZhu="備註";
var Font_BiSaiRiQi="比賽日期";
var Font_SheZhiPingBi="設置屏蔽";
var Font_ZuiMoYe="最末頁";
var Font_CQ_Ten="十位";
var Font_GuanWangYingPMobile="官網影片";
var Font_ChaKan="查看";
var Font_ChaXun="查詢";
var Font_CacheUpdate="緩存更新";
var Font_FuCai3D="福彩3D";
var Font_CaiQiu="彩球";
var Font_CaoZuo="操作";
var Font_FuLeQiu="福樂球";
var Font_MuQianBiSaiMYZB="目前沒有比賽直播";
var Font_JiangHao="獎號";
var Font_SaiMaJieGuo="賽馬結果";
var Font_GengGaiMiMa2="更改密碼";
var Font_YinCangHonLi="隱藏紅利";
var Font_TSGameDY="TS游戏记录调阅";
var Font_CQ_Extra20="2區特號";
var Font_TaiWanCaiJuan="台灣彩券";
var Font_ZhuangTai="狀態";
var Font_JiShiGengXin="即時更新";
var Font_TaoLunQu="討論區";
var Font_XuanZe="選擇";
var Font_Mei10MiaoGX="每10秒更新";
var Font_RuQiuShu="入球數";
var Font_TouZhuEDuXYSY="投注額度不可以大於剩餘額度！";
var Font_TouZhuEDuDYDD="投注額度不可以大於單隊限制！";
var Font_TouZhuEDuDYDC="投注額度不可以大於本場總注額！";
var Font_MaxSixChips="最多設置六個籌碼";
var Font_ShangBanChangGQDS1="";
var Font_ShangBanChangGQDX1="";
var Font_ShangBanChangGQRF1="";
var Font_ShouRangTeam="受讓隊伍";
var Font_ShangBanChangBiShu="上半場比數";
var Font_XiBaLe="喜八樂";
var Font_XiuGai="修改";
var Font_XiaZhu="下注";
var Font_XiaBan="下半";
var Font_XiaoXi="消息";
var Font_XianShangLiuYan="線上留言";
var Font_CaiQiuGongGao1="";
var Font_LTCQJJKF="樂透彩球即將開放，敬請期待，謝謝！";
var Font_SuoYouZhenRen1="所有真人";
var Font_ZuiDiTouZhuEMobile="最低投注額";
var Font_HuiYuanDengChu="會員登出";
var Font_GunQiuBanQuanChang2="半全場<br/>（含滾球）";
var Font_ZhongSanQBS="中三[千百十]";
var Font_FanHuiJSLT="返回即時聊天";
var Font_Language="ZH";
var Font_QuanBuGongGao1="";
var Font_Schedule="節目表";
var Font_YouXi2="遊戲";
var Font_YouXi1="遊戲";
var Font_TaiWanDaLeTou="台灣大樂透";
var Font_ShangJiXianZhiTY="上級限制停押";
var Font_JieLong2="接&nbsp;龍";
var Font_BetTime_EN="下注時間";
var Font_FaSong="發送";
var Font_FanHui="返回";
var Font_FanTan="番攤";
var Font_GZPKXS="各種分盤口顯示";
var Font_KeFuZhuanQu="客服專區";
var Font_YuFuWuQiDKLJ="該賽事已結束，系統自動登出，請重新連接！";
var Font_GuanFangWangZhan="官方網站";
var Font_FenYeXiaoJi="分頁小計";
var Font_TongZuHe="";
var Font_LianPengErX="連碰二星";
var Font_CQ_Total6="6粒總和";
var Font_CQ_Total7="7粒總和";
var Font_CQ_Total4="4粒總和";
var Font_CQ_Total5="5粒總和";
var Font_CQ_Total3="3粒總和";
var Font_SiZhongErPeiLv="四中二賠率";
var Font_ChatTitle="客服中心";
var Font_BenZhangHaoYouXiZhong="本帳號還在遊戲中, 您暫時無法下注！";
var Font_ZuQiuGongGao1="";
var Font_ShangJiWeiKaiFZH="上級未開放綜合過關！";
var Font_JiangHaoZongShu="獎號總數";
var Font_SanZhongSanPeiLv="三中三賠率";
var Font_FSZTZE="總投注額";
var Font_GunQiu="滾球";
var Font_GuanBi="關閉";
var Font_FSGong="共";
var Font_FSCGZS="組數";
var Font_FSCGWF="玩法";
var Font_BingQiuGongGao="冰球公告";
var Font_WXSanJie="三節";
var Font_WenZiJianShu14="表示讓分隊伍贏受讓隊伍3分時押讓分隊伍全輸，4分全贏。";
var Font_WenZiJianShu11="表示讓分隊伍贏受讓隊伍3分時押讓分隊伍贏50%，4分全贏。";
var Font_WenZiJianShu10="表示讓分隊伍贏受讓隊伍2分時押讓分隊伍全輸，3分全贏。";
var Font_WenZiJianShu13="表示讓分隊伍贏受讓隊伍3分時押讓分隊伍輸50%，4分全贏。";
var Font_WenZiJianShu12="表示讓分隊伍贏受讓隊伍3分時兩隊平手，4分全贏。";
var Font_PiaoHaoMRTZJE="選擇啟用,投注完第一筆金額為100注單后,再投注第二筆注單,此时金額不需用手動輸入數值,會自動填入數值100,依此類推.";
var Font_HongKaQuXiao="紅卡錯誤取消";
var Font_ReMenPaiXu="熱門排序";
var Font_YunDongXingYongEDu="體育信用額度";
var Font_3DDianZiGuan1="";
var Font_YiJieSuan="已結算";
var Font_WangQiuGongGao="網球公告";
var Font_DiErPan="第二盤獲勝者";
var Font_DiErZhu="第二柱:";
var Font_DiErJie="第二節";
var Font_JiXianBiaoSu2="極&nbsp;限&nbsp;飆&nbsp;速";
var Font_AGIJiaKouDian="綜合電子館加扣點";
var Font_HuiYuanZhangHao2="會員帳號";
var Font_CQ_Thousands="千位";
var Font_JiZhunFen="基準分";
var Font_TianXiaYunDongW="天下運動網";
var Font_FastBetTitle="快速投注";
var Font_DiWuPan="第五盤獲勝者";
var Font_ZhuKeDuiWu="主客隊伍";
var Font_ZhuKeChang="主客場";
var Title_GongGaoZhuanQu="公告專區";
var Font_DiSiPan="第四盤獲勝者";
var Font_DiSiJie="第四節";
var Font_FastBetOpen1="您已開啟快速下注模式\n\n設置投注金額後\n\n點擊賠率即刻進行投注";
var Font_ShanChuXuanZhong="刪除選中";
var Font_DiYiPan="第一盤獲勝者";
var Font_DiYiZhu="第一柱:";
var Font_DiYiJie="第一節";
var Font_ShouPanJia="收盤價";
var Font_TaiBang2="台&nbsp;棒";
var Font_TaiBang1="台棒";
var Font_WangQiu2="網&nbsp;球";
var Font_WangQiu1="網球";
var Font_ChangCiMobile="場次";
var Font_SaiMaGuoGuan="賽馬過關";
var Font_GuanKanZhong="觀看中";
var Font_DiaoYue="調閱";
var Font_GuanKanYingP="觀看影片";
var Font_ZuSanX="組三星";
var Font_ZuQiu2="足&nbsp;球";
var Font_ZuQiu1="足球";
var Font_ZuoFei="作廢";
var Font_ZuiGao="最高";
var Font_SanChongCai="三重彩";
var Font_SuoYouYunDong1="所有體育";
var Font_QuanMobile="全";
var Title_ZiXun="";
var Font_DanJieZuiGaoDF1="單節最高得分";
var Font_PeiLvBianDong="賠率可能隨時變動";
var Title_Rules="規則";
var Font_ZongJi="總計";
var Font_ZongHe="總和";
var Font_ZhuNum="柱";
var Font_ZhuZhu="主/主";
var Font_Zhong1="中";
var Font_ZhiShu="指數";
var Font_YouXiGongGao1="";
var Font_CustomChips="自訂籌碼";
var Title_Links="相關網站";
var Font_DuoXuanBuZhong="多選不中";
var Title_GuiZe="九卅體育--規則";
var Font_XianShiTZCGXX="顯示投注成功信息";
var Font_GongGao="公告";
var Font_QueRenXiaZhu="確認下注";
var Font_QueRenXiuGai="確認修改";
var Font_PianHaoSheDing="偏好設定";
var Font_BetsAmount="投注金額";
var Font_CCFWQCXSRSXTJ="超出範圍,請重新輸入搜尋條件!";
var Font_MoRenTouZhuJinE="默認投注金額";
var Font_YiZhiLiuQiu2="（第1至6球）";
var Font_PaiQiu="排球";
var Font_PaiJiu="牌九";
var Font_PanShu="盤數獲勝者";
var Font_PanKou="盤口";
var Font_XianShangDuiZhang="線上對戰";
var Font_SaiMaDuYing="賽馬獨贏";
var Font_QuXiao="取消";
var Font_QuanBu="全部";
var Font_FSCGYuan="元";
var Font_ShiFouKaiFang="是否開放";
var Font_XiangGuanWangZhan2="相關網站";
var Font_QiYong="啟用";
var Font_GuoGuanTouZhu="過關投注";
var Font_QiuLei="球類";
var Font_DiYiJieRangFen="單節讓分";
var Font_MeiZhouGJB="美洲杯";
var Font_GunQiuRuQiuShu2="全場/半場<br/>入球數<br/>（含滾球）";
var Font_SuoYouZhenRen="九卅真人(細項)";
var Font_PingBiMingDan="屏蔽名單";
var Font_QiTaGongGao1="";
var Font_BiSaiMeiYouKFGG="比賽沒有開放過關!";
var Font_BiSaiMeiYouKFDS="比賽沒有開放單式";
var Font_JiuSaHuiFu="<br>九卅回覆：";
var Font_TianXieBuYiZhi="填寫不一致！";
var Font_QuXiaoXiaZhu="取消下注";
var Font_Dengru1="登入";
var Font_DengChu="登&nbsp;出";
var Font_CQ_SGFour="第4球";
var Font_CQ_SGFive="第5球";
var Font_WeiJieSuan="未結算";
var Font_Deposit="存";
var Font_SiXiaoLianZhong="四肖連[中]";
var Font_MuQianBiShu="目前比數";
var Font_MuQianLTSRS="目前聊天室人數";
var Font_XianShiGZDXXNR="顯示更早的訊息內容";
var Font_XuanZheSaiMaZH="請選擇賽馬組合";
var Font_ShangBanChangRF="上半場<br />讓&nbsp;分";
var Font_ShangBanChangDS="上半場<br />單&nbsp;雙";
var Font_ShangBanChangDX="上半場<br />大&nbsp;小";
var Font_ShangBanChangDY="上半場<br />獨&nbsp;贏";
var Font_AGIPointsChanged="綜合電子館加扣點";
var Font_TaiBangGongGao="台棒公告";
var Font_ZuiGaoYaZhu="最高押注";
var Font_ZhuangTaiZai="狀態：";
var Font_ChongQingKaiXinCai="重慶開心彩";
var Font_ZuiDiTouZhuE="最低投注額";
var Font_GunQiuZhong="滾球中";
var Font_YuXiaXie="魚蝦蟹";
var Font_GunQiuShuJu="滾球數據";
var Font_GunQiuBoDan="滾球波膽";
var Font_MiaoZDGX="";
var Font_GeWeiShu="個位數";
var Font_TouZhu="投注";
var Font_YunDongYXTZ="體育有效投注";
var Font_YunDongWang="TS運動網";
var Font_TiKuan="提款";
var Font_ZuiGaoTouZhuEMobile1="最高投注";
var Font_TianEr="天二";
var Font_Fanhuishangyiye="返回上一個頁面";
var Font_ErXiaoLianZhong="二肖連[中]";
var Font_XiangGangLiuHeCai="香港六合彩";
var Font_DiQiJuWinner="第七局獲勝者";
var Font_DaLaoEr="大老二";
var Font_GuoJiPeiLv2="國際賠率";
var Font_GuoJiPeiLv4="國際賠率";
var Font_TaiQiu="撞球";
var Font_TaiWan="台灣";
var Font_TaiHao="台號";
var Font_NinDeTouZhuVI3="";
var Font_NinDeTouZhuVI2="";
var Font_HuiYuanMingCheng2="會員名稱";
var Font_NinDeZhangHaoYBJZFY="您的帳號已被禁止發言！";
var Font_DaXiao2="大小";
var Font_DaXiao1="大小";
var Font_ChongqingShiShiCai="重慶時時彩";
var Font_BanChangRangFenDX="半場讓分大小";
var Font_GengXin="更新";
var Font_NinDeTouZhu="是您的投注";
var Font_DangWei="檔位";
var Font_QXWCSJYZ="請先完成手機號碼驗證!";
var Font_DanHao2="單<span style='margin-left: 24px;'></span>號";
var Font_DanShi2="單   式";
var Font_DaiDing="待定";
var Font_SSFXSJ="賽事分析數據";
var Font_TuiChuBiSai="退出比賽";
var Font_ZiDongSXPL="自動刷新賠率";
var Font_BanChangRangFenDX1="";
var Font_GeGuoGuan="個過關";
var Font_RiBang="日棒";
var Font_ZuiGaoTouZhuE="最高投注額";
var Font_BiSaiShiJian2="比賽時間";
var Font_WuZhongSiPeiLv="五中四賠率";
var Font_Result="輸贏結果";
var Font_ShouWeiFen="首尾分";
var Font_DiSanJie2="第三節";
var Font_DiSanMing="第三名";
var Font_CunKuan="存款";
var Font_BiShaiLeiXing="比賽類型";
var Font_GunQiuRangFen="滾球讓分";
var Font_GunQiuRangQiu="滾球讓球";
var Font_Submit="提交";
var Font_Status="分盤狀況";
var Font_SiXing="四星";
var Font_DiWuJuWinner="第五局獲勝者";
var Font_ShuoHa="梭哈";
var Font_Shuang="雙";
var Font_Shang1="上";
var Font_ShouBi="(手臂)";
var Font_ShiXun="視訊";
var Font_8c1="8串1";
var Font_9c1="9串1";
var Font_151="1.5";
var Font_153="1輸";
var Font_152="一球半";
var Font_3c1="3串1";
var Font_3c4="3串4";
var Font_051="0.5";
var Font_052="半球";
var Font_053="0輸";
var Font_7c1="7串1";
var Font_7PK="7PK";
var Font_4c1="4串1";
var Font_5c1="5串1";
var Font_5PK="5PK";
var Font_2c1="2串1";
var Font_Hao="號";
var Font_He1="和";
var Font_He2="合";
var Font_Hou="後";
var Font_Huo="火";
var Font_6c1="6串1";
var Font_Lan="藍";
var Font_Ji1="奇";
var Font_Jin="金";
var Font_Kai="開";
var Font_Niu="牛";
var Font_OZB="歐洲杯";
var Font_Ou1="偶";
var Font_Da1="大";
var Font_Da2="大";
var Font_Dan="單";
var Font_Bai="百";
var Font_Xia="下";
var Font_Ye1="頁";
var Font_Yi1="一";
var Font_Fen="分";
var Font_Gou="狗";
var Font_Zhu="（主）";
var Font_Pig="豬";
var Font_Pan="盤";
var Font_Qiu="球";
var Font_Qi1="七";
var Font_Tu2="兔";
var Font_Tie="平";
var Font_Shu="輸";
var Font_She="蛇";
var Font_Shi="十";
var Font_San="三";
var Font_Win="全贏";
var Font_Wei="尾";
var Font_Wan="(萬)";
var Font_SaiBao="骰寶";
var Font_SaiGuo="賽果";
var Font_SaiGou="賽狗";
var Font_SaiMa2="賽&nbsp;馬";
var Font_SaiMa3="賽馬/賽狗";
var Font_SaiMa1="賽馬";
var Font_SanJie="三節";
var Font_3HuoYiShang="3或以上";
var Font_JinPingMei="金瓶梅";
var Font_Screen="視頻";
var Font_SaiMaSaiQiBiao="賽馬賽期表";
var Font_MeiYouZhangHu="沒有該帳戶！";
var Font_FangWeiPan="方位盤";
var Font_MiPaiBaiJiaLe1="竞眯";
var Font_ShiWanZhangHaoSM="試玩帳號，將以訪客身份進入聊天室，造成不便，敬請見諒!!!";
var Font_JiShiBiFen="即時比分";
var Font_DanZhuXiaXian="單注下限";
var Font_QuanBuQuXiao="全部取消";
var Font_SaiMaLianYing="賽馬連贏";
var Font_GengGaiMiMa="新密碼";
var Font_FanhuiJiuBan="返回舊版";
var Font_ZongShu="總數";
var Font_XiangGuanWangZhan="相關網站";
var Title_GameBill_GetSuperMoney="獲得超級彩金：";
var Font_ShowTiYuSaiShi="展開體育賽事";
var Font_ZhuangXian="莊閒";
var Font_ShuiGuoPan2="水&nbsp;果&nbsp;盤";
var Font_ZongHeGuoGuanMobile="綜合過關";
var Font_GengXin1="更新";
var Font_ZhengQiZhuXiao="整期註銷";
var Font_GaoErFu="高爾夫";
var Font_SplitMaintainImages="../../Images/SplitW_ZH.gif";
var Font_QingZhuCe="請註冊會員後方能觀看現場轉播!!";
var Font_DengRuShouYe="登入首頁";
var Font_BaXuanBuZhong="八選不中";
var Font_Selections="關數";
var Font_ZhiShu1="指數";
var Font_ZhiShu2="指&nbsp;數";
var Font_WanQianBai="萬千百";
var Font_ZhangWu="帳務";
var Font_MeiBangMobile="美棒";
var Font_ZhengMa="正碼";
var Font_ZhenRen="真人";
var Font_WN8888="溫哥華運動網---會員介面";
var Font_WXXiaGun="下滾";
var Font_WXXiaBan="下半";
var Font_BanChangRangQiu="半場讓球";
var Font_BanChangRangFen="半場讓分";
var Font_ShangZhouHeJi1="上週合計";
var Font_DiErJuWinner="第二局獲勝者";
var Font_YiBeiJieShou="已被接受";
var Font_TouZhuZuHePeng="[投注組合(碰)列表]";
var Font_XianShiXZQRXX="顯示下注確認信息";
var Font_YuSheGuoGuanTouZhuJE="預設過關投注金額";
var Font_YuanMiMa="原密碼";
var Font_WuZhongWuPeiLv="五中五賠率";
var Font_WeiShu="位數";
var Font_WeiZhi="位置";
var Font_OGJiaKouDian="OG加扣點";
var Font_XunXiTiaoShu="共0條訊息";
var Font_ShangYiYe="上一頁";
var Font_3DDianZiGuan="3D电子馆";
var Font_PeiLvLeiXing="賠率類型";
var Title_News="公告專區";
var Font_YiZhiLiuQiu="第1至6球";
var Title_Bill_Info_Immediate="注單訊息";
var Font_PHZuiXinZhuDan="最新注單";
var Font_YouZuiXinGRXX="您有最新的個人訊息!";
var Font_HongLiDianShu="紅利點數";
var Font_GuanBiShiChuang="關閉視窗";
var Font_ZiDongXiaZhu="自動下注";
var Font_SaiMaGongGao="賽馬/賽狗公告";
var Font_ShuJuJiaZaiZhong="數據加載中";
var Font_SaiQiBiao="賽期表";
var Font_XunXiNeiRong="訊息內容";
var Font_RuYouYiWenQQSJ="如有疑問請洽上級.謝謝";
var Font_SelectAllOfAlliance="全部聯賽";
var Font_ShuYingJinE="輸贏金額";
var Font_BBinJKDS="BBIN加扣點";
var Font_YingChao="英超";
var Font_TiYuBoCaiMobile="體育博彩";
var Font_HaiMeiYouGRXX="還沒有個人信息!";
var Font_WXShangBanZQ="上半";
var Font_BanChangDaXiao="半場大小";
var Font_ZongFenHuoDeZhe="總分獲勝者";
var Font_QiTaBiFen="其他比分";
var Font_QiTaBiSai="其他比賽";
var Font_CQ_SGSeven="第7球";
var Font_DiShiMing="第十名";
var Font_CQ_SGThree="第3球";
var Font_MiMaCuoWu="密碼錯誤，密碼連續8次填寫錯誤帳戶將被鎖定！";
var Font_ShangJiWeiKaiFang="上級未開放！";
var Font_Basketball="其他籃球";
var Font_GuanWangYingP="官網影片";
var Font_BanChangDuYing="半場獨贏";
var Font_YiChangZhuDanQX="異常注單取消";
var Font_MiMaTiShi="6-10碼,前2碼為英文.";
var Font_TongZuHeZGPCMobile="最高可贏金額";
var Font_MeiYeXianShi20B="每頁顯示20筆";
var Font_MeiYeXianShi40B="每頁顯示40筆";
var Font_MeiYeXianShi60B="每頁顯示60筆";
var Title_SaiGuo="九卅體育--比賽結果";
var Font_DepositTitle="存款";
var Font_NinQueDingYaoDYYXM="您確定要調閱遊戲嗎？";
var Font_XianShiLTS="顯示聊天室";
var Font_XianShiYuE="顯示餘額";
var Font_JiaoYiFanMang="交易繁忙...請重新下注....";
var Font_SaiGouGuoGuan="賽狗過關";
var Font_QuanBuXuanZe="全部選擇";
var Font_XianShiHonLi="顯示紅利";
var Font_DiSiJuWinner="第四局獲勝者";
var Font_SiXingCai="四星彩";
var Font_QiTaGongGao="其他公告";
var Font_FaSongXXBNWK="發送消息不能為空，請重新輸入";
var Font_ErZhongErPeiLv="二中二賠率";
var Font_kaiJiangJieGuo="開獎結果";
var Font_MuQianKaiFangSS="目前開放賽事";
var Font_ReturnOfPrincipal="退回本金";
var Font_GunQiuDuYingMobile="滾球獨贏";
var Font_QuanChangDuYingHGQ2="全場獨贏<br />（含滾球）";
var Font_QuanChangDuYingHGQ1="";
var Font_YiZhiWuJu="1~5局";
var Font_JieChuJinYanShiBai="解除禁言失敗！";
var Font_DuYing1="獨贏";
var Font_DuYing3="獨贏";
var Font_DuYing2="獨贏";
var Font_DuYing4="獨贏";
var Font_XuanHao="選號";
var Font_XuanDan="選單";
var Font_BiSaiMYKFGQ="比賽沒有開放滾球！";
var Font_ZaiXianDianShi="在線電視";
var Font_TYCQYXTZ="體育/彩球<br/>有效投注";
var Font_ZBPDYDSX="直播頻道已達上限,請關閉頻道再行添加.";
var Font_YiZhuXiao="已註銷";
var Font_TianErSan="天二三";
var Font_WoDeQianBao="平台轉帳";
var Font_KaiXinCai="開心彩";
var Font_MessegesOfHourseRacingBet="賽馬投注信息";
var Font_SheWeiMRTZJEMobile="設為默認投注金額";
var Font_XiaBanChang="下半場";
var Font_KeYongEDu="可用額度";
var Font_HundredUnknownSymbol="百分數為未知符號，請輸入數字";
var Font_DuiZhan="對戰";
var Font_DuiMing="隊名";
var Font_ZuiShao2Guan="·最少2關, 最多10關.<br />·點擊投注內容關數下方[X]，可以取消所選隊伍.";
var Font_RiBenSaiQiBiao="日本賽期表";
var Font_XuanZeLianMeng="選擇聯盟";
var Font_CeShiGuangChang="測試廣場";
var Font_SaiMaGongGao1="";
var Font_ZhanKaiTiYu="展開體育";
var Font_DiYiJieDanShuang1="";
var Font_HuiYuanMingCheng="會 員 名 稱";
var Title_ZhangWuZhongXin="帳務中心";
var Font_SaiGuoBiShu="賽果比數";
var Font_FaSongBiaoQingBNCG6G="發送表情不能超過6個";
var Font_100Bets="100筆";
var Font_LanWangQiu="籃網球";
var Font_Xuanzezuijiaxianlu="選擇最佳線路";
var Font_TiaoXunXi="條訊息";
var Font_MeiBangTouZhu="美棒投注";
var Font_AlertSZXX="您輸入的數值不能低於2位高於6位！";
var Font_BettingLimit="投注限額";
var Font_QiShuDaiHao="期數代號";
var Font_JiaZaiShiBai="加載失敗，請關閉重試...";
var Font_YiZhiWuQiu2="（第1至5球）";
var Font_JiangXiShiShiCai="江西時時彩";
var Font_MiMaBuNengWeiKong="密碼不能為空！";
var Font_HuiYuanZiLiao2="會員資料";
var Font_XianYaoTouBao="先搖骰寶";
var Font_ZhenRenShengYuEDu="真人剩餘額度";
var Font_XiaBanChangGQDS1="";
var Font_XiaBanChangGQDX1="";
var Font_XiaBanChangGQRF1="";
var Font_10c1013="10串1013";
var Font_GuShiMingCheng="股市名稱";
var Font_QuXiaoXiaZhuMobile="取消下注";
var Font_SiZhongSiPeiLv="四中四賠率";
var Font_XinDaLaoEr="新大老二";
var Font_ZhaoYunJiuZhu2="趙&nbsp;雲&nbsp;救&nbsp;主";
var Font_NinBeiPoXiaXian="您被強迫下線，您的帳戶在其他位置登入！";
var Font_TupianName="zh_";
var Font_JuXiaBan="局&nbsp;下半";
var Font_FSMeiZu="每組";
var Font_SuoYouShiXunLYX="所有視訊類遊戲";
var Font_LieYinCiYeMian="列印此頁面";
var Font_GunQiu2="滾   球";
var Font_BaiJiaLeJackpotS="手臂百家Jackpot";
var Font_BaiJiaLeJackpot2="百&nbsp;家&nbsp;jackpot";
var Font_GuoGuan="過關";
var Font_GuanBi2="關 閉";
var Font_GuanJun="冠軍";
var Font_ShaBaJiaKouDian="沙巴加扣點";
var Font_ZuHePaiCai="◎ 同組合最高派彩";
var Font_BiaoTiNRBNWK="標題與內容不可為空!";
var Font_FSCGZGY="總共有";
var Font_FSCGGTZ="個投注";
var Font_ShangBanChang1="上半場";
var Font_ShangBanChang2="上半場";
var Font_ShangBanChang3="上半場";
var Font_DouDiZhu2="鬥&nbsp;地&nbsp;主";
var Font_TouZhuEDuDYDZ2="投注額度不可以小於最低投注額！";
var Font_TouZhuEDuDYDZ1="投注額度不可以大於最高投注額！";
var Font_QuanChangGunQiuQC="全場滾球";
var Font_TianJinShiShiCai="天津時時彩";
var Font_HuiYuanZhiLiao="會員資料";
var Font_XianChangZhuanBo="現場轉播";
var Font_GameType="遊戲類型";
var Font_ZhangWuZhuanYiZhong="帳務轉移中，請稍後！";
var Font_WanChengXuanGuanDJXZ="完成選關 點擊下注";
var Font_HuiYuanZhuanQu="會員專區";
var Font_ZhangHaoBuNengWeiKong="帳號不能為空！";
var Font_ZhuYiShaiMa="注意：所有賽馬/賽狗比賽結果以各官方網站所公佈文字檔為最後派彩依據";
var Font_WXRuQiuShu="入球數";
var Font_DouJiJiaKouDian="鬥雞加扣點";
var Font_LiuHeCaiJieGuo="六合彩結果";
var Font_MeiShiPeiLv="美式賠率";
var Font_DaiDingZhong="待定中";
var Font_ZuQiuZaoCan="足球早餐";
var Font_LiShiZhangWu="歷史帳務";
var Title_XunXiZhuanQu="訊息專區";
var Font_ShiFouQDSC="是否確定要刪除?";
var Font_DuoQiTouZhu="多期投注";
var Font_WXBanQuanChang="半全場";
var Font_ShangBanChangGunQ="上半場滾球";
var Font_ShangBanChangGQDS="上半場<br />滾球單雙";
var Font_ShangBanChangGQDX="上半場<br />滾球大小";
var Font_ShangBanChangGQRF="上半場<br />滾球讓分";
var Font_HuiYuanZhangHao="會 員 帳 號";
var Font_SiZhongSanPeiLv="四中三賠率";
var Font_BetUnder="下注小分";
var Font_ZhongChang="中場";
var Font_ZuHeTouZhu="組合投注";
var Font_SiGuoJunQi="四國軍棋";
var Font_DanJieZuiGaoRangFen="單節<br/>最高得分";
var Font_QiangShou="搶首";
var Font_TouZhuGunQiu="滾球";
var Font_JinRiNinMeiYYXZD="今日您沒有遊戲注單.";
var Font_JinRiNinMeiYQLZD="今日您沒有球類注單.";
var Font_JinRiTouZhuMX="今日投注明細";
var Font_HuanYing="歡迎";
var Font_BetMoney1000="以賠率0.90下注，下注金額為$1,000";
var Font_QingZhuYiTiShiPLBD="\n\n    請注意：比賽賠率信息已經發生改動，系統已自動投注最佳賠率，您確定要下注嗎？";
var Font_ShengXiao="生肖";
var Font_BianDongXX="日後如需變動設定，請至會員資料更改。";
var Font_JiaZaiPinDaoLBZ="加載頻道列表中";
var Font_TiYanJin="體驗金";
var Font_ZuanShiMember="鑽石會員";
var Font_PHZhanKaiTY="展開體育";
var Font_TiYuWang="體育網";
var Font_BanChangDanShuang1="";
var Font_PHLianMengPX="联盟排序";
var Font_BingQiuGongGao1="";
var Font_TianJinKaiXinCai="天津開心彩";
var Font_PEnterStake="請輸入金額";
var Font_PHBingQiu="冰球";
var Font_QueDingMobile="確定";
var Font_GuanBiShangMianDeGuangGao="關閉上面的廣告";
var Font_BenChangZongZhuEr="本場總注額";
var Font_LeTouCaiQiu="六合彩球";
var Font_ShangBanChangGunQBD="上半場滾球";
var Font_WenZiJianShu4="表示讓分隊伍贏受讓隊伍1分時兩隊平手，2分全贏。";
var Font_WenZiJianShu5="表示讓分隊伍贏受讓隊伍1分時押讓分隊伍輸50%，2分全贏。";
var Font_WenZiJianShu6="表示讓分隊伍贏受讓隊伍1分時押讓分隊伍全輸，2分全贏。";
var Font_WenZiJianShu7="表示讓分隊伍贏受讓隊伍2分時押讓分隊伍贏50%，3分全贏。";
var Font_WenZiJianShu1="表示讓分隊伍跟受讓隊伍平手時，讓分隊伍輸50%。";
var Font_WenZiJianShu2="表示讓分隊伍跟受讓隊伍平手時，讓分隊伍全輸。";
var Font_WenZiJianShu3="表示讓分隊伍贏受讓隊伍1分時押讓分隊伍贏50%，2分全贏。";
var Font_WenZiJianShu8="表示讓分隊伍贏受讓隊伍2分時兩隊平手，3分全贏。";
var Font_WenZiJianShu9="表示讓分隊伍贏受讓隊伍2分時押讓分隊伍輸50%，3分全贏。";
var Font_BuTongZhangWu_TS="不同帳務日期的賽事不能同時過關！";
var Font_TouZhuChengGong="投注成功";
var Font_NoDeposit="您尚未儲值，儲值後即可觀看，謝謝！";
var Font_BetAmountCanbeMoreThanCreditAmount="投注額度不可以大於信用額度";
var Font_ZuDiTouZhuEr="最低投注額";
var Font_ShangBanChangRF1="";
var Font_ShangBanChangDS1="";
var Font_TaiWanBinGuoZhiBo="台灣賓果直播";
var Font_ShuRuJinEBBHXS="輸入的金額不能包含小數！";
var Font_GuoGuanBiSaiCF="過關比賽重複 , 請重新下注 !";
var Font_XiangQiMaJiang="象棋麻將";
var Font_GaiYongHuBuCunZai="該用戶不存在！";
var Font_HuiDaTing="回大廳";
var Font_WuZhongSanPeiLv="五中三賠率";
var Font_ShiSanZhi2="十&nbsp;三&nbsp;支";
var Font_YouZuiXinFaBuGG="有最新發佈的即時公告 !!!!!!!!\n請點擊上面的跑馬燈觀看最新公告詳細內容.";
var Font_ShuangLianP="雙連碰";
var Font_TaiWan16ZhangMJ="台灣16張麻將";
var Font_DuYingReporrt="獨贏";
var Font_ShengYuEDu="剩餘額度";
var Font_XiuGaiCG="修改成功！";
var Font_XiuGaiSB="修改失敗！";
var Font_ZongHeGuoGuanTZ="綜合過關投注";
var Font_JinJiMember="金級會員";
var Font_MeiZuGongGao1="";
var Font_ZongHeQiuLei="綜合球類";
var Font_WinningSuanFa2="（贏50%）<span id='result_box'><span title='可贏金額' closure_hashcode_c3y16r='101'>可贏金額</span></span>=1,000X0.900X50%=$450";
var Font_MuQianWuTYSS="<目前無體育賽事>";
var Font_JiaJie1="加時";
var Font_JiaNaDa="加拿大";
var Font_XieXieNSBGYJ="謝謝您的寶貴意見 客服人員將在24小時之內回覆您!";
var Font_JieLong="接龍";
var Font_JieGuo2="結&nbsp;果";
var Font_JieGuo3="結  果";
var Font_FaSongXXBNCG200Z="發送消息不能超過200字";
var Font_DiYiJieDuYing1="";
var Font_SUNJiaKouDian="";
var Font_JiuMiMa="舊密碼";
var Font_HanBangMobile="其他棒球";
var Font_ZhuKeChangDeF="主客場總得分";
var Font_QuanChangDuYingHGQ="全場獨贏<br />（含滾球）";
var Font_YiZhiWuQiu="第1至5球";
var Font_LanQiuGongGao1="";
var Font_DouDiZhu="鬥地主";
var Font_ZuiGaoPaiCai="◎ 每注最高派彩以 100 萬為上限.";
var Font_ZhenRenXinYongEDu="真人信用額度";
var Font_WinningSuanFa="=1,000x0.900=$900";
var Font_XiuGaiBingDengLu="修改並登入";
var Font_QingXuanZe="請選擇";
var Font_BeiJingJNC="北京基诺彩";
var Font_ZhuKeDui="主客隊";
var Font_JiuSaZhenRen="九卅真人";
var Font_TouZhuJiLu="投注記錄";
var Font_TouZhuJinE="投注金額";
var Font_TouZhuZuHe="投注組合";
var Font_BianDongXX2="日後如需變動設定，請至偏好設定更改";
var Font_DiSanJieMobile="第三節";
var Tilte_OldVersion="切換舊版";
var Font_TSGuangChang="TS廣場";
var Font_JinRiTongji="今日統計";
var Font_QuanChang="全場";
var Font_XiYouJi="西遊記";
var Font_XiXiang="(細項)";
var Font_ZhangWuZhongXin="帳務中心";
var Font_LianPeng="連碰";
var Font_LianYing="連贏";
var Font_ShiXuanBuZhong="十選不中";
var Font_WenZiMiaoShu="表示<span class='MFS_colorB'>讓分隊伍</span>贏<span class='MFS_colorG'>受讓隊伍</span>3分時，押<span class='MFS_colorB'>讓分隊伍</span>全輸，4分全贏。";
var Font_YouXiXinYongEDu="遊戲信用額度";
var Font_TouZhuMingXi="投注明細";
var Font_QianShiQiSPJ="前十期收盤價歷史記錄";
var Font_JinYanShiBai="禁言失敗！";
var Font_ShangBan="上半";
var Font_WoTongYiZhunS="我同意遵守";
var Font_10Srefresh="10秒更新";
var Font_SubHeaDings="菲律賓合法網投CEZA企業註冊號NO.CF-163　　中文客服電話";
var Font_TKGNZBKF="很抱歉 目前提款功能暫不開放 謝謝!";
var Font_XFPBaiJiaLe="百家樂";
var Font_HouSanBSG="後三[百十個]";
var Font_HanBang1="其他棒球";
var Font_HanBang2="其他棒球";
var Font_TianErLianPeng="天二連碰";
var Font_SheWeiMRTZJE="設為默認投注金額";
var Font_SiQuanZhong="4星(四全中)";
var Font_YiChaoGuoDaDui="已超過單隊上限...\n\n請稍候...";
var Font_SuoYouDuiZhanLYX="所有對戰類遊戲";
var Font_XinMiMa="新密碼";
var Font_ShiXuanZhongYi="十選中一";
var Font_XiaYiYe="下一頁";
var Font_WXQiangWei="搶尾";
var Font_YXFWGZYYD="以下服務規則已閱讀<br/>並同意";
var Font_lianMaShi="練馬師";
var Font_XiangQi="象棋";
var Font_ZhuangTaiGongNeng="狀態功能";
var Font_DeZhouPuKe="德州撲克";
var Font_DanJuZongYa="單局總押";
var Font_Withdrawal="提";
var Font_MiMaJianDanTiShi="您的密碼過於簡單，為了您的密碼安全，請重新設置您的密碼，請在下面修改您的密碼，請輸入長度超過4位，並且是字母和數字的組合.";
var Font_SanXingCai="三星彩";
var Font_TeShuYuLe="特殊娛樂";
var Font_ZhongFei="總分";
var Font_SaiGuChuiNiu="骰盅吹牛";
var Font_ZhengZaiChuLi="正在處理";
var Font_ZongRuQiuShu="總入球數";
var Font_TouZhuShiBai="投注失敗";
var Font_ZhenRenDZPK2="真&nbsp;人&nbsp;德&nbsp;州&nbsp;撲&nbsp;克";
var Font_GoBetRecord="請至<a class='BettingSuccess_Note02' href='#'>投注記錄</a>查詢";
var Font_30Srefresh="30秒更新";
var Font_DuYingZQ="獨贏";
var Font_MaCheSai="馬車賽";
var Font_XingQiEr="星期二";
var Font_XingQiYi="星期一";
var Font_XingQiSi="星期四";
var Font_XingQiWu="星期五";
var Font_XingQiRi="星期日";
var Font_Transfer="轉";
var Font_RiBang1="日棒";
var Font_RiBang2="日&nbsp;棒";
var Font_WangYeXunXi="網頁訊息";
var Font_SanGong2="三&nbsp;公";
var Font_QueRenNinDeTouZhu="確認您的投注";
var Font_ZhangWuRiQi="帳務日期";
var Font_ShangJiWeiKaiFangGG="上級未開放過關！";
var Font_ShengYin="提示聲";
var Font_MuQianMeiYouBSKF="目前沒有比賽開放投注";
var Font_OtherRules="其他規則請至各種賽事相關規則查詢。";
var Font_LeTouCaiQiuMobile="六合彩球";
var Font_ZhenRenDZPK="真人德州撲克";
var Font_AlertSZXX2="您輸入的數值不能低於3位高於6位！";
var Font_AlertSZXX1="您輸入的數值不能高於6位！";
var Font_WenZiMiaoShu13="表示<span class='MFS_colorB'>讓分隊伍</span>跟<span class='MFS_colorG'>受讓隊伍</span>平手時，押<span class='MFS_colorB'>讓分隊伍</span>輸50%。";
var Font_WenZiMiaoShu12="表示<span class='MFS_colorB'>讓分隊伍</span>跟<span class='MFS_colorG'>受讓隊伍</span>平手時，<span id='result_box'><span title='壓' closure_hashcode_c3y16r='37'>押</span></span><span class='MFS_colorB'>讓分隊伍</span>全輸。";
var Font_WenZiMiaoShu11="表示<span class='MFS_colorB'>讓分隊伍</span>贏<span class='MFS_colorG'>受讓隊伍</span>1分時，押<span class='MFS_colorB'>讓分隊伍</span>贏50%，2分全贏。";
var Font_WenZiMiaoShu10="表示<span class='MFS_colorB'>讓分隊伍</span>贏<span class='MFS_colorG'>受讓隊伍</span>1分時，兩隊平手，2分全贏。";
var Font_WenZiMiaoShu14="表示互不相讓，贏1分全贏。";
var Font_ZhuKeChangZongDF="主客場總得分";
var Font_XiaBanChangRF="下半場<br />讓&nbsp;分";
var Font_XiaBanChangDS="下半場<br />單&nbsp;雙";
var Font_XiaBanChangDY="下半場<br />獨&nbsp;贏";
var Font_XiaBanChangDX="下半場<br />大&nbsp;小";
var Font_ZhuYiShaiMa2="澳門賽狗比賽結果以官方網站（https://newbet.macaudog.com/betindex.do）即時賽果為最後派彩依據，後續若對賽果有爭議，本公司將不予認可。";
var Font_HundredDigitCannotBeEmpty="百分數不能為空！";
var Font_JiaJuMobile="加局";
var Font_EXAMPLES="範　　例";
var Font_WXQuanChang1="全場";
var Font_WeiGongBu="未公佈";
var Font_YuLeChangAPP="娛樂場APP";
var Font_ZhuangTaiZai1="";
var Font_XiaZhuChengGong="下注成功！\n請至[投注記錄]查詢！";
var Font_XiaZhuShiBai="下注失敗！";
var Font_MinBetMoney="最低投注";
var Title_Settings="功能設定";
var Font_ZuHePaiCaiSX="萬為上限";
var Font_FaBuShiJian="發佈時間";
var Font_TaoLiZhuDanQX="套利注單取消";
var Font_NoVoidBet="目前沒有作廢注單";
var Title_Bill_Content_Immediate="投注内容";
var Font_AnEnterJianFSXX="按Enter鍵發送消息";
var Font_TSYYunDongWang="TS運動網";
var Font_ShuiGuoPan="水果盤";
var Font_ShengYuEDuBuZu="剩餘額度不足！";
var Font_Youaccounthasbeenlocked="您的帳號已被鎖定";
var Font_WeiXiaZhuSM2="您如果於 48 小時內未下注 , 將無法進入 觀看 各類 精彩 影片 , 造成不便 , 敬請見諒 !!!";
var Font_HuiYuanZhangHaoMobile="會員帳號";
var Font_QieHuanPinDao="切換頻道";
var Font_CaoDiGunQiu="草地滚球";
var Font_WXQiangShou="搶首";
var Font_DiSiJieMobile="第四節";
var Font_TianSanLiZhu="天三立柱";
var Font_TongYiFuWuGuiZe="請先同意服務規則再登录！";
var Font_HasBeenRejected="已被取消";
var Font_XiangQi2="象&nbsp;棋";
var Font_XiaoMaLi="小瑪麗";
var Font_PHReMenPX="熱門排序";
var Font_PMDMessageText="選擇啟用，有新訊息發佈時跳提示框提醒；選擇不啟用，將不會跳提示框，公告頁面直接顯示出最新訊息";
var Font_WagerMustBeHigher="本金必須大於0";
var Font_DaXiaoDanShuang="大小單雙";
var Font_SiLianHuan="四連環";
var Font_CaiQiuXiMaLiang2="彩球洗碼量";
var Font_XunXiLeiBie="訊息類別";
var Font_ClearCache="清緩存";
var Font_ShangHaiShiShiLe="上海時時樂";
var Font_ZuiJinZhangWu="最近帳務";
var Font_QiuSaiZhongXin="球賽中心";
var Font_ShiJian3="時　　間:";
var Font_ShiJian2="時<span style='margin-left: 24px;'></span>間";
var Font_ZNXLXZZ="智能線路選擇中";
var Font_QiangShouWei="搶首搶尾";
var Font_QiangShouFen="搶首分";
var Font_TianSanLianPeng="天三連碰";
var Font_BaXuanZhongYi="八選中一";
var Font_YingXiong="英雄";
var Font_WXBoDan="波膽";
var Font_JinQiuDanQuXiao="進球單取消";
var Font_WXErJie="二節";
var Font_XuanQuZhuangTai="選取狀態";
var Font_DaSehenJi="大神級";
var Font_QingWuShuRu="請勿輸入";
var Font_YouxiZhudan="遊戲注單";
var Font_WXSiJie="四節";
var Font_BroadcastRights="很抱歉,您沒有進入觀看賽事直播的權限.";
var Font_TianXieMiMaBYZ="填寫密碼不一致！";
var Font_SwitchLine="切換線路";
var Font_YiLianMengPX="聯盟排序";
var Font_WXYiJie="一節";
var Font_GunQiuDanShuang2="滾球單雙";
var Font_YanZhengMaShuRCW="驗證碼輸入錯誤！";
var Font_ZuoRiTouZhuMX="昨日投注明細";
var Font_NotInclude="所有種類賽事讓分.大小.獨贏.一輸二贏.單雙...等之賠率為不含本金之賠率，敬請會員下注時注意.";
var Font_LiveChat="真人聊天";
var Font_YouXiShengYuEDu="遊戲剩餘額度";
var Font_ZhangHao="帳號";
var Font_YouXiNeiRong="遊戲內容";
var Font_ZongShuTouZhu="投注總數";
var Font_MeiYe20Peng="每頁20碰";
var Font_WeiHuZhong="目前維護中，請稍後再進入，謝謝！";
var Font_RangQiu="讓球";
var Font_RangFen="讓分";
var Font_WanWeiShu="萬位數";
var Font_LianPengKuaiSu="連碰快速";
var Font_8Xing="八星";
var Font_8c247="8串247";
var Font_XiangGangSaiQiBiao="香港賽期表";
var Font_9c502="9串502";
var Font_9Xing="九星";
var Font_3Xing="三星";
var Font_3_501="3/3.5";
var Font_3_502="三球/三球半";
var Font_3_503="3-50";
var Font_1Xing="一星";
var Font_4Xing="四星";
var Font_PhoneLive="現場轉播";
var Font_7c120="7串120";
var Font_7Xing="七星";
var Font_GunQiuBanQuanChangSX="滾球半全場";
var Font_2Xing="二星";
var Font_2_501="2.5/3";
var Font_2_503="3+50";
var Font_2_502="二球半/三球";
var Font_XunXiGongGao="訊息公告";
var Font_5Xing="五星";
var Font_HaoMa="號碼";
var Font_HeZhu="和/主";
var Font_HeZhi="和值";
var Font_Huang="黃";
var Font_HBJKD="HB加扣點";
var Font_666VL="緯來運動網--會員介面";
var Font_6Xing="六星";
var Font_LiKai="離開";
var Font_MeiZu="美足";
var Font_MaHao="馬號";
var Font_MiMa2="密  碼";
var Font_MoShi="模式";
var Font_YiShuErYing="一輸二贏";
var Font_JinJi="金級";
var Font_JinRi="今日";
var Font_JiaJu="加局";
var Font_JiaCu="加粗";
var Font_JuShu="局數獲勝者";
var Font_KeZhu="客/主";
var Font_JZLHC="九卅六合彩";
var Font_AnQi2="暗&nbsp;棋";
var Font_AoMen="澳門";
var Font_NoSay="您於48小時內未下注,將無法發言,造成不便,敬請見諒!!!";
var Font_NvLan="女籃";
var Font_OuShu="偶數";
var Font_OuLan="歐籃";
var Font_EHaiE="俄亥俄";
var Font_Dian2="靛";
var Font_DaKai="開啟";
var Font_DuiWu="隊伍";
var Font_DuiZi="對子";
var Font_Empty="清空";
var Font_Elite="尊榮級";
var Font_OddsChanged="賠率或盤口已變更";
var Font_TouZhuXinXi2="投注信息";
var Font_ErJie="二節";
var Font_BoDan="波膽";
var Font_BiFen="比分";
var Font_BiShu="比數";
var Font_BiQiu="壁球";
var Font_BetNo="投注單號";
var Font_Chang="場";
var Font_Cheng="橙";
var Font_Clear="清零";
var Font_CuoWu="錯誤";
var Font_XuHao="序號";
var Font_XinXi="信&nbsp;&nbsp;&nbsp;&nbsp;息";
var Font_Xiao2="小";
var Font_Xiao1="小";
var Font_QueDingXiaZhu="確定下注";
var Font_YaJun="亞軍";
var Font_YiShu="一輸";
var Font_YiJie="一節";
var Font_XLYQH="線路已切換 !";
var Font_YouXi="遊戲";
var Font_GS888="金天下運動網---會員介面";
var Font_FuShi="複式";
var Font_PiaoHaoYSGGTZJE1="选择启用,将以设定后的金额投注过关及综合过关赛事(數值不能低於2位,高於6位).";
var Font_GuShi="股市";
var Font_GuiZe="規則";
var Font_ZuQiu="足球";
var Font_ZuoRi="昨日";
var Font_ZuiDi="最低";
var Title_SongLiTime="時間";
var Font_ZiXun="資訊";
var Font_ZhuKe="主/客";
var Font_ZhuHe="主/和";
var Font_ZhuZi="珠仔";
var Font_ZhuYi="注意";
var Font_Zhong="（中）";
var Font_ZhiBo="直播";
var Font_ZZLJZ="正在連接中......";
var Font_ZBWHZ="現場直播維護中, 請稍後進入. 謝謝!";
var Font_DeZhouPuKe2="德&nbsp;州&nbsp;撲&nbsp;克";
var Font_PaoMa="跑馬";
var Font_PeiLv="賠率";
var Font_Quan1="全";
var Font_QiTa2="其&nbsp;他";
var Font_QiTa3="其他";
var Font_QiCai="七彩";
var Font_QiuSe="球色";
var Font_Qiang="搶";
var Font_PMDTS="跑馬燈提示";
var Font_ShangShangZhouHeJi="上上週合計";
var Title_PianHaoSheDing="九卅體育--偏好設定";
var Font_TiYu2="&nbsp;&nbsp;體育";
var Font_TeSan="特三";
var Font_TSCai="TS彩";
var Font_RiBen="日本";
var Font_RiLan="日籃";
var Font_SD777="新樂園運動網---會員介面";
var Font_Split="分割";
var Font_SiJie="四節";
var Font_Shang="上";
var Font_Shou1="首";
var Font_ShiGe="十個";
var Font_RB888="紅興運動網RB888---會員介面";
var Font_SaiMa="賽馬/賽狗";
var Font_SeDie="色碟";
var Font_TiYuZhuDan="體育注單";
var Font_PiaoHaoYSGGKYJE1="选择启用,将以设定后的可赢金额投注过关及综合过关赛事(數值不能低於2位,高於6位).";
var Font_WeiQi="圍棋";
var Font_ShangZhongXiaPan="上中下盤";
var Font_SuoYouDianZiLYX="所有電子類遊戲";
var Font_XianChangYouXi="現場遊戲";
var Font_DaXiaoDanShuangErXChuanGuan="大小單雙二星串關";
var Font_ZongHeGuoGuan1="綜合過關";
var Font_ZongHeGuoGuan2="綜&nbsp;合&nbsp;過&nbsp;關";
var Font_ZongHeGuoGuan3="綜合&nbsp;過關";
var Font_ShuangKou="雙扣";
var Font_CreditBetIsSuccess1="投注成功";
var Font_ZYXJZHYFY="對不起，聊天室只允許九卅會員發言!";
var Font_HanBang="其他棒球";
var Font_CunKuanHongLi="存款红利";
var Font_QieHuanXinBan="切換新版";
var Font_ZongHeGuoGuan="綜合過關";
var Font_EnterStake="輸入金額";
var Font_QueDing1="確&nbsp;&nbsp;&nbsp;定";
var Font_QueDing2="確&nbsp;&nbsp;定";
var Font_ZiTiDaXiao="字體大小";
var Font_XiaZhuJinETD="下注金額太低";
var Font_XiaZhuJinETS="下注金額超出了本場总注額，請重新輸入下注金額！";
var Font_FanShuiBPan="返水B盤";
var Font_FanShuiAPan="返水A盤";
var Font_FanShuiCPan="返水C盤";
var Font_ZhongGuoMeiRen="中國美人";
var Font_ZhangHao2="帳  號";
var Font_XiaBanChangRF1="";
var Font_XiaBanChangDS1="";
var Font_XiaBanChangDY1="";
var Font_XiaBanChangDX1="";
var Font_TiYuBoCai="體育博彩";
var Font_OddsMustBe="賠率必須大於0";
var Font_TransferTitle="平臺轉帳";
var Font_BiShaiShiJian="比賽時間";
var Font_DanJieZuiGao="單節最高";
var Font_GunQiuZhong2="滾球中";
var Font_SanMaSaiGou1="賽馬/賽狗";
var Font_XiTongGongGao="系統公告";
var Font_SuoYouCaiQiu="所有彩球(細項)";
var Font_DiYiJieDaXiao1="";
var Font_DanShuang1="單雙";
var Font_DanShuang2="單雙";
var Font_ZuiXinZhuDan="最新注單";
var Font_SetStake="設定投注金額";
var Font_XiaHuaXian="下劃線";
var Font_BuKeYiJinYanZiJi="不可以禁言自己！";
var Font_TaiWan16ZhangMJ2="台&nbsp;灣&nbsp;16&nbsp;張&nbsp;麻&nbsp;將";
var Font_YuShegGuoGuanKeYingJE="預設過關可贏金額";
var Font_GunQiuDuYing1="滾球獨贏";
var Font_GunQiuDuYing2="滾球獨贏";
var Font_WuMaWeiShu="五碼位數";
var Font_PaiWeiBiao="排位表";
var Font_DaShenMember="大神會員";
var Font_EHaiEZhouJNC="俄亥俄州基諾彩";
var Font_MeiYePeng="每頁100碰";
var Font_Settings="功能設定";
var Font_DianZiJingji="電子競技";
var Font_QuanJiGD="拳擊/格鬥";
var Font_QuanXuan="全選";
var Font_SiXiaoLianBuZhong="四肖連[不中]";
var Font_KouLiuBeiDi="扣六倍底";
var Font_AnCtrlEJianFSXX="按Ctrl+Enter鍵發送消息";
var Font_ChongXuan="重選";
var Font_HeiHong="黑紅";
var Font_FgspWeiHu="分割視頻維護中，請稍後再進入，謝謝！";
var Font_WeiMobile="尾";
var Font_GuanYaZuHe="冠亞軍組合";
var Font_WoDeZuiAi1="我的最愛";
var Font_NiuNiu2="牛&nbsp;牛";
var Font_YiYingZhuDan="已贏注單";
var Font_QiXuanZhongYi="七選中一";
var Font_BuQiYong="不啟用";
var Font_AlertSwitchLine="很抱歉，系統發生未預期的錯誤。\n請聯繫客服人員，我們會盡快為您處理";
var Font_BuYunXuSRWZ="不允許輸入網址，請重新輸入.";
var Font_SaiMaXiaoShuDianH1WMS="小數點後1位秒數";
var Font_ZongHeGuoGuanXTYXM="綜合過關不允許全部下注同一個項目！";
var Font_Youhaveloggedout="您已登出";
var Font_QADHYXTSJ="親愛的會員，您好：\\n很抱歉，存款系統目前進行維護作業 \\n請稍候再使用此功能";
var Font_JiXianBiaoSu="極限飆速";
var Font_CQ_SGSix="第6球";
var Font_CQ_SGTwo="第2球";
var Font_CQ_SGOne="第1球";
var Title_TiYuBoCai="九卅體育";
var Font_11="1";
var Font_12="一球";
var Font_13="1平";
var Font_3X="三肖";
var Font_32="三球";
var Font_33="3平";
var Font_31="3";
var Font_1X="一肖";
var Font_01="0";
var Font_03="pk";
var Font_02="平手";
var Font_4X="四肖";
var Font_23="2平";
var Font_22="二球";
var Font_21="2";
var Font_2X="二肖";
var Font_5X="五肖";
var Font_He="和";
var Font_Hu="虎";
var Font_6X="六肖";
var Font_Li="六";
var Font_Lv="綠";
var Font_Ma="馬";
var Font_Mu="木";
var Font_Ji="雞";
var Font_Di="第";
var Font_Da="大";
var Font_Er="二";
var Font_Ye="頁";
var Font_Yi="一";
var Font_Ge="個";
var Font_Zi="紫";
var Font_Qi="期";
var Font_Tu="土";
var Font_Te="特";
var Font_Ri="日";
var Font_Si="四";
var Font_Wu="五";
var Font_TuiTongZi="推筒子";
var Font_TiYuSaiShi="體育賽事";
var Font_SplitImages="../../Images/Split_ZH.gif";
var Font_SuoYouGunQiu="所有滾球";
var Font_SaiMaMingCheng="賽馬名稱";
var Font_MuQianMeiYouZuiXinZhuDan="目前沒有最新注單";
var Font_DiYiJieDanShuang="單節單雙";
var Font_DuoRenChuiNiu="多人吹牛";
var Font_BanChangDanShuang="半場單雙";
var Font_XiaZhuJinETS2="下注金額超出了最高投注額，請重新輸入下注金額！";
var Title_Bill_KeYing="可贏";
var Font_WangQiuGongGao1="";
var Font_ShouCangJia="我的最愛";
var Font_MeiBang2="美&nbsp;棒";
var Font_MeiBang1="美棒";
var Font_BanChangDaXiao1="";
var Font_DiErJie1="第二節";
var Font_DiErJie2="第二節";
var Font_DiErMing="第二名";
var Font_ZhangHuLiShi="帳戶歷史";
var Font_SuoYouDianZi1="所有電子";
var Font_UpperLimitGame="本場上限";
var Font_BanChangDuYingHGQ="半場獨贏<br />（含滾球）";
var Font_AlertZheShiGunQiuTouZhu="***********這是滾球投注***********\n狀態在\"等待中\"是您的投注\"正在處理\"\n狀態在\"已確認\"是您的投注\"已被接受\"\n請您稍做等待目前正在審核您的注單\n請重複按刷新已確認您的投注,謝謝";
var Font_ErXingZuXuanFenWei="二星組選分位";
var Font_PayableAmountSuanfa="（輸50%）<span id='result_box'><span title='輸付金額' closure_hashcode_c3y16r='101'>輸付金額</span></span>=-1,000X50%=$-500";
var Font_BangQiuGongGao="棒球公告";
var Font_QuanChangGunQiu="全場滾球";
var Font_DivZheShiGunQiuTouZhu="<h2 class='BL' style=\"margin-left: 14px;\"><strong class='sDZZ'>等待中.......</strong> 是您的投注<strong>正在處理</strong></h2><h2 class='GR' style=\"margin-left: 14px;\"><strong class='sDZZ'>已確認.......</strong> 是您的投注<strong>已被接受</strong></h2><h2 class='RED'style=\"margin-left: 14px;\"><strong class='sDZZ'>投注拒絕...</strong> 是您的投注<strong>已被取消<br/></strong></h2><p style=\"position: absolute;padding: 0px;left: 38px;top: 100px;font-size: 14px;\">目前正在審核您的注單，請注意您的注單狀態</p>";
var Font_DanChangShangXian="單場上限";
var Font_PingPangQiu="乒乓球";
var Font_DanShuangHGQ="所有單雙";
var Font_Logout16="偵測到重複登入，已將您登出";
var Title_Bill_FanShui="返水";
var Font_XiangGanLiuHeCai="香港馬會(六合彩)";
var Font_PHGuoJiPL="國際賠率";
var Font_DiLiuJuWinner="第六局獲勝者";
var Font_TaiWan38LeHeCai="台灣38樂合彩";
var Font_HeNeiShiShiCai="河內時時彩";
var Font_ShouBiCheMaP="手臂車馬炮";
var Font_ShiShiCai="時時彩";
var Font_BuKaiFang="不開放";
var Font_JiuMiMaSRCW="舊密碼輸入錯誤!";
var Font_ShiSanZhi="十三支";
var Font_DiYiJieDuYing="單節獨贏";
var Title_Bill_DanHao="單號";
var Font_NoWaitingBet="目前沒有等待中注單";
var Font_ShowPanJieGuo="收盤結果";
var Font_PuKePai="撲克牌";
var Font_DiYiJieDaXiao="單節大小";
var Font_GunQiuRangFen2="滾球讓分";
var Font_ZongHeChuanGuan="綜合串關";
var Font_DESCRIPTIONS="操作說明";
var Font_SuoYouDianZi="所有電子(細項)";
var Font_Olympics="奧運會";


function tableHeaderDS(ballSx, dyn, rfn, dxn, dsn, ysey, qsf, qwf, djzgrf, headType, bShowHalf, tblId, bShowZhiBo, isSingle) {
    var tdNameLeft = "";
    var tdNameRight = "";
    var colTd = "";
    var colSbcTd = "";
    var tdNum = 0;
    var tdSbcNum = 0;
    switch (headType) {
        case 1:
            tdNameLeft = Font_WXQuanChang;
            tdNameRight = Font_ShangBan;
            break;
        case 2:
            tdNameLeft = Font_DiYiJieMobile;
            tdNameRight = Font_DiErJieMobile;
            break;
        case 3:
            tdNameLeft = Font_DiSanJieMobile;
            tdNameRight = Font_DiSiJieMobile;
            break;
        case 5:
            tdNameLeft = Font_WXQuanChang;
            tdNameRight = Font_DuoZhongWanFa;
            break;
        case 6:
            tdNameLeft = Font_ShangBan;
            tdNameRight = Font_XiaBan;
            break;
        case 8:
            tdNameLeft = Font_WXQuanChang;
            tdNameRight = "";
            break;
        case 9:
            tdNameLeft = Font_ShangBan;
            tdNameRight = "";
            break;
        case 10:
            tdNameLeft = Font_XiaBan;
            tdNameRight = "";
            break;
    }

    //美足全部单行为下半
    if ((ballSx == "mz" || ballSx == "ot" || ballSx == "lq") && !bShowHalf && bShowZhiBo) {
        tdNameLeft = Font_XiaBan;
        tdNameRight = "";
    }
    if (isSingle != undefined && isSingle) {
        tdNameRight = "";
        switch (headType) {
            case 0:
            case 8:
                tdNameLeft = Font_WXQuanChang;
                break;
            case 1:
                tdNameLeft = Font_ShangBan;
                break;
            case 2:
                tdNameLeft = Font_XiaBan;
                break;
            case 6:
                tdNameLeft = Font_DanJie;
                break;
            case 11:
                tdNameLeft = Font_DiYiJie;
                break;
            case 12:
                tdNameLeft = Font_DiErJie;
                break;
            case 13:
                tdNameLeft = Font_DiSanJie;
                break;
            case 14:
                tdNameLeft = Font_DiSiJie;
                break;
        }
    }
    for (var i = 0; i < 2; i++) {
        var strSceneName = i == 0 ? tdNameLeft : tdNameRight;
        var tdWanFaName = i == 0 ? "tdBallLeft" : "tdBallRight";
        if (i == 0 || (i == 1 && bShowHalf && headType != "5" && strSceneName != "")) {
            var title = ""; //越南语详解
            var titlevi = "";
            if (Font_Language == "VI") {
                if (strSceneName == Font_WXQuanChang) {
                    title = Font_QuanChang1;
                } else if (strSceneName == Font_ShangBan) {
                    if (ballSx == "zq") {
                        title = Font_ShangBanChang2;
                    } else {
                        title = Font_WXShangBan;
                    }
                } else if (strSceneName == Font_XiaBan) {
                    title = Font_XiaBanChang;
                } else if (strSceneName == Font_DiYiJie) {
                    title = Font_DiYiJieMobile;
                } else if (strSceneName == Font_DiErJie) {
                    title = Font_DiErJie1;
                } else if (strSceneName == Font_DiSanJie) {
                    title = Font_DiSanJie1;
                } else if (strSceneName == Font_DiSiJie) {
                    title = Font_DiSiJie1;
                }
                if (strSceneName == Font_DanJie) {
                    strSceneName = Font_DanJie + " ";
                }
                title = title + " ";
            }
            if (Font_Language == "EN") {
                strSceneName = strSceneName + " ";
            }
            //足球独赢
            if (ballSx == "zq" && dyn != 0) {
                if (title != "") {
                    titlevi = title + Font_DuYingZQ;

                    colTd += "<td title='" + titlevi + "' nowrap name=" + tdWanFaName + " ><span class='ColumnTitle'>" + "&nbsp;" + strSceneName + Font_DuYingZQ + "&nbsp;" + "</span></td>";
                } else {
                    colTd += "<td nowrap name=" + tdWanFaName + " ><span class='ColumnTitle'>" + "&nbsp;" + strSceneName + Font_DuYingZQ + "&nbsp;" + "</span></td>";
                }

                tdNum++;
            }
            //让分
            if (rfn != 0) {
                if (title != "") {
                    titlevi = title + Font_RangFen1;
                }
                colTd += "<td title='" + titlevi + "' nowrap name=" + tdWanFaName + "><span class='ColumnTitle'>";
                colTd += "&nbsp;" + strSceneName + ((ballSx == "zq" && Font_Language != "VI") ? Font_RangQiu : Font_RangFen) + "&nbsp;";
                colTd += "</span></td>";
                tdNum++;
            }
            //大小
            if (dxn != 0) {
                if (title != "") {
                    titlevi = title + Font_DaXiao1;
                }
                colTd += "<td title='" + titlevi + "' nowrap name=" + tdWanFaName + "><span class='ColumnTitle'>" + "&nbsp;" + strSceneName + Font_DaXiao + "&nbsp;" + "</span></td>";
                tdNum++;
            }
            //独赢
            if (ballSx != "zq" && dyn != 0) {
                if (title != "") {
                    titlevi = title + Font_DuYing4;
                }
                colTd += "<td title='" + titlevi + "' nowrap name=" + tdWanFaName + "><span class='ColumnTitle'>" + "&nbsp;" + strSceneName + Font_DuYing2 + "&nbsp;" + "</span></td>";
                tdNum++;
            }
            //一输二赢,只有全场有
            if (ysey != 0 && $.trim(strSceneName) == Font_WXQuanChang) {
                if (Font_Language == "VI") {
                    titlevi = Font_YiShuErYing;
                }
                colTd += "<td title='" + titlevi + "' nowrap name=" + tdWanFaName + "><span class='ColumnTitle'>" + "&nbsp;" + strSceneName + Font_YiShu + "&nbsp;" + "</span></td>";
                tdNum++;
            }
            //单双
            if (dsn != 0) {
                if (title != "") {
                    titlevi = title + Font_DanShuang1;
                }
                colTd += "<td title='" + titlevi + "' nowrap name=" + tdWanFaName + "><span class='ColumnTitle'>" + "&nbsp;" + strSceneName + Font_DanShuang + "&nbsp;" + "</span></td>";
                tdNum++;
            }
        }
    }

    var headTr = "<tr class='TitleBGDs " + (Font_Language == "EN" ? " enfont" : "") + "' valign='middle' align='center'>";
    headTr += "<td name='tdGameDate'  nowrap=''>";
    if (ballSx != "zs") {
        headTr += "<span  class='ColumnTitle'>" + Font_BiShaiShiJian + "</span></td>";
    }
    else {
        headTr += "<span  class='ColumnTitle'>" + Font_ShiJian + "</span></td>";
    }
    headTr += "<td  name='tdZK" + tblId + "' align='center' nowrap ><span class='ColumnTitle'>";
    if (ballSx == "ss") {
        headTr += Font_MingCheng;
    }
    else if (ballSx == "zs") {
        headTr += Font_GuShiMingCheng;
    }
    else {
        headTr += Font_ZhuKeDui;
    }
    headTr += "</span></td>";
    headTr += colTd + colSbcTd;
    headTr += !bShowZhiBo ? "" : "<td nowrap name='tdLive' title='" + (Font_Language == "VI" ? Title_ZiXun : '') + "' class='ColumnTitle' valign='middle' align='center'>" + Font_ZiXun;
    headTr += "</td>";
    headTr += "</tr>";
    public_lmColSpan = tdNum + tdSbcNum + (!bShowZhiBo ? 2 : 3);
    return headTr;
}

//拼接赛事表头 滚球
function tableHeaderZd(ballSx, dyn, rfn, dxn, dsn, jzf, headType, bShowHalf, tblId, bShowZhiBo) {
    var tdNameLeft = "";
    var tdNameRight = "";
    var tdNum = 0;
    var tdNumsbc = 0;
    var colTd = "";
    var colTdsbc = "";
    switch (headType) {
        case 4:
            tdNameLeft = Font_WXQuanChang;
            tdNameRight = Font_WXShangBanZQ;
            break;
        case 7:
            tdNameLeft = Font_WXShangBanZQ;
            tdNameRight = Font_XiaBan;
            break;
        case 1:
        case 8:
            tdNameLeft = Font_WXQuanChang;
            tdNameRight = "";
            break;
        case 9:
            tdNameLeft = Font_WXShangBanZQ;
            tdNameRight = "";
            break;
        case 10:
            tdNameLeft = Font_XiaBan;
            tdNameRight = "";
            break;
    }
    for (var i = 0; i < 2; i++) {
        var strSceneName = i == 0 ? tdNameLeft : tdNameRight;
        var tdWanFaName = i == 0 ? "tdBallLeft" : "tdBallRight";
        if (i == 0 || (i == 1 && bShowHalf && tdNameRight != "")) {
            var title = ""; //越南语详解
            var titlevi = "";
            if (Font_Language == "VI") {
                if (strSceneName == Font_WXQuanChang) {
                    title = Font_QuanChang1;
                } else if (strSceneName == Font_WXShangBanZQ) {
                    if (ballSx == "zq") {
                        title = Font_ShangBanChang2;
                    } else {
                        title = Font_WXShangBan;
                    }
                } else if (strSceneName == Font_XiaBan) {
                    title = Font_XiaBanChang;
                }
                title = title + " ";
                if (ballSx == "zq" && i > 0) {
                    strSceneName = strSceneName + " ";
                }
            }

            //全场
            if (ballSx != "zq" && jzf > 0) {
                tdNum++;
                colTd += "<td nowrap=\"nowrap\" class=ColumnTitle name=" + tdWanFaName + " >" + "&nbsp;" + strSceneName + Font_BiFen + "&nbsp;" + "</td>";
            }
            if (ballSx == "zq" && dyn != 0) {
                tdNum++;
                if (title != "") {
                    titlevi = title + Font_GunQiuDuYing1;
                    if (Font_Language == "VI") {
                        titlevi = title + Font_GunQiuDuYingVI;
                    }
                }
                colTd += "<td title='" + titlevi + "' nowrap=\"nowrap\" class=ColumnTitle name=" + tdWanFaName + " >" + "&nbsp;" + strSceneName + Font_GunQiuDuYing + "&nbsp;" + "</td>";
            }
            if (rfn != 0) {
                tdNum++;
                if (title != "") {
                    titlevi = title + Font_GunQiuRangFen2;
                }
                colTd += "<td title='" + titlevi + "' nowrap=\"nowrap\" class=ColumnTitle name=" + tdWanFaName + " >";
                colTd += "&nbsp;" + strSceneName + (ballSx == "zq" ? Font_GunQiuRangQiu : Font_GunQiuRangFen) + "&nbsp;";
                colTd += "</td>";
            }
            if (dxn != 0) {
                tdNum++;
                if (title != "") {
                    titlevi = title + Font_GunQiuDaXiao2;
                }
                colTd += "<td title='" + titlevi + "' nowrap=\"nowrap\" class=ColumnTitle name=" + tdWanFaName + " >" + "&nbsp;" + strSceneName + Font_GunQiuDaXiao + "&nbsp;" + "</td>";
            }
            if (ballSx != "zq" && dyn != 0) {
                tdNum++;
                if (title != "") {
                    titlevi = title + Font_DuYing1 + Font_GunQiu;
                }
                colTd += "<td title='" + titlevi + "' nowrap=\"nowrap\" class=ColumnTitle name=" + tdWanFaName + " >" + "&nbsp;" + strSceneName + Font_GunQiuDuYing2 + "&nbsp;" + "</td>";


            }
            if (dsn != 0) {
                tdNum++;
                if (title != "") {
                    titlevi = title + Font_GunQiuDanShuang2;
                }
                colTd += "<td title='" + titlevi + "' nowrap=\"nowrap\" class=ColumnTitle name=" + tdWanFaName + " >" + "&nbsp;" + strSceneName + Font_GunQiuDanShuang + "&nbsp;" + "</td>";
            }
        }
    }
    var headTr = "<TR class=\"TitleBGZd" + (Font_Language == "EN" ? " enfont" : "") + "\" VALIGN=\"middle\" align=\"center\" >";
    headTr += "<td name='tdGameDate' class=ColumnTitle nowrap='' >" + Font_BiShaiShiJian + "</td>";
    headTr += "<td class='ColumnTitle' name='tdZK" + tblId + "' align=\"center\">" + Font_ZhuKeDui + "</td>";
    headTr += colTd;
    headTr += colTdsbc;
    headTr += !bShowZhiBo ? "" : "<td title='" + (Font_Language == "VI" ? Title_ZiXun : '') + "' name='tdLive' align=\"center\" valign=\"middle\" class=ColumnTitle>" + Font_ZiXun + "</td>";
    headTr += "</tr>";
    public_lmColSpan = tdNum + tdNumsbc + (!bShowZhiBo ? 2 : 3);
    return headTr;
}
