database:
  username: root
  password: 123456
  host: localhost
  name: ftodds
  pool: 5
  timeout: 5000
  port: 3306
  encoding: utf8
  maxidleconns: 10
  maxconns: 10
  logmode: false
redis:
  host: localhost
  port: 6379
  index: 0
notify:
  slackenable: false
http:
  addr: :18086
  pingaddr: http://127.0.0.1:18086